apiVersion: v1
kind: Service
metadata:
  name: autossl
  namespace: "{{ meta.namespace }}"
  labels:
    app: autossl
    part-of: 3scale-saas
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ external_dns_hostname }}"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "{{ load_balancer.proxy_protocol | default (load_balancer_proxy_protocol) }}"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "{{ load_balancer.cross_zone_load_balancing_enabled | default (load_balancer_cross_zone_load_balancing_enabled) }}"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "{{ load_balancer.connection_draining_enabled | default (load_balancer_connection_draining_enabled) }}"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "{{ load_balancer.connection_draining_timeout | default (load_balancer_connection_draining_timeout) }}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "{{ load_balancer.connection_healthcheck_healthy_threshold | default (load_balancer_connection_healthcheck_healthy_threshold) }}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "{{ load_balancer.connection_healthcheck_unhealthy_threshold | default (load_balancer_connection_healthcheck_unhealthy_threshold) }}"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "{{ load_balancer.connection_healthcheck_interval | default (load_balancer_connection_healthcheck_interval) }}" 
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "{{ load_balancer.connection_healthcheck_timeout | default (load_balancer_connection_healthcheck_timeout) }}"
{% if load_balancer.access_log_enabled is defined and load_balancer.access_log_enabled == true %}
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "{{ load_balancer.access_log_enabled }}"
{% if load_balancer.access_log_emit_interval is defined %}
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "{{ load_balancer.access_log_emit_interval }}"
{% endif %}
{% if load_balancer.access_log_s3_bucket_name is defined %}
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "{{ load_balancer.access_log_s3_bucket_name }}"
{% endif %}
{% if load_balancer.access_log_s3_bucket_prefix is defined %}
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "{{ load_balancer.access_log_s3_bucket_prefix }}"
{% endif %}
{% endif %}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    deployment: autossl
