apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: autossl
  namespace: "{{ meta.namespace }}"
  labels:
    app: autossl
    part-of: 3scale-saas
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_service_label_app
          targetLabel: app
  selector:
    matchLabels:
      deployment: autossl
