{
 "title": "{{ meta.namespace }} / 3scale System AutoSSL",
 "tags": [
  "3scale",
  "autossl",
  "system"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "{{ meta.namespace }}" }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain validations (last 24h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(autossl_domains_allowed{namespace='$namespace', pod=~'autossl.*'}[24h])) by (status)",
     "legendFormat": "{{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Let's encrypt issued certificates (last 24h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(autossl_letsencrypt_requests{namespace='$namespace', pod=~'autossl.*'}[24h])) by (status)",
     "legendFormat": "{{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Autossl Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_http_connections{namespace='$namespace', pod=~'autossl.*'}) by (state)",
     "legendFormat": "{{ '{{' }}state{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Prometheus Metrics Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_metric_errors_total{namespace='$namespace', pod=~'autossl.*'})",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'autossl.*'}"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'autossl.*'}"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'autossl.*'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'autossl.*'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace='$namespace',deployment=~'autossl.*'}",
     "legendFormat": "total-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'autossl.*'}",
     "legendFormat": "avail-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'autossl.*'}",
     "legendFormat": "unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'autossl.*'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'autossl.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'autossl.*'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'autossl.*'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'autossl.*', container!=''}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'autossl.*', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'autossl.*', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'autossl.*', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'autossl.*'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace', pod=~'autossl.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace', pod=~'autossl.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  }
 ]
}