apiVersion: v1
kind: Service
metadata:
  name: backend-listener
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: listener
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    deployment: backend-listener
  type: ClusterIP
