{
 "title": "{{ meta.namespace }} / 3scale Backend Storage Node",
 "tags": [
  "3scale",
  "backend",
  "storage",
  "node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree{instance=~\"$node\",job=~\"$job\"}) / (node_memory_SwapTotal{instance=~\"$node\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=~\"$node\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time{instance=~\"$node\",job=~\"$job\"} - node_boot_time{instance=~\"$node\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu{mode=~\".*irq\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree{instance=~\"$node\",job=~\"$job\"} - (node_memory_Cached{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  { "title": "Basic Net / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "recv {{ '{{' }}device{{ '}}' }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "trans {{ '{{' }}device{{ '}}' }} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size{instance=~\"$node\",job=~\"$job\",device!~'rootfs'})",
     "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Memory Net Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree{instance=~\"$node\",job=~\"$job\"} - node_memory_Buffers{instance=~\"$node\",job=~\"$job\"} - node_memory_Cached{instance=~\"$node\",job=~\"$job\"} - node_memory_Slab{instance=~\"$node\",job=~\"$job\"} - node_memory_PageTables{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapCached{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{ '{{' }}device{{ '}}' }} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{ '{{' }}device{{ '}}' }} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{ '{{' }}device{{ '}}' }} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_bytes_written{instance=~\"$node\",job=~\"$job\"}[5m])",
     "legendFormat": "{{ '{{' }}device{{ '}}' }} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node\",job=~\"$job\"} [5m])",
     "legendFormat": "{{ '{{' }}device{{ '}}' }} - Milliseconds spent doing I/Os"
    }
   ]
  },
  {
   "title": "Memory Detail Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Bounce",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Bounce{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Bounce - Memory used for block device bounce buffers"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      }
     ]
    },
    {
     "title": "Memory DirectMap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "short", "label": "Pages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Operations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgdeactivate{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgdeactivate - Pages moved from active to inactive"
      },
      {
       "expr": "irate(node_vmstat_pgfree{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgfree - Page free operations"
      },
      {
       "expr": "irate(node_vmstat_pgactivate{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgactivate - Pages moved from inactive to active"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Faults" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=~\"$node\",job=~\"$job\"}[5m])  - irate(node_vmstat_pgmajfault{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgminfault - Minnor page fault operations"
      }
     ]
    },
    {
     "title": "Memory Pages Reclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_kswapd_inodesteal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Kswapd_inodesteal - Pages reclaimed via kswapd inode freeing"
      },
      {
       "expr": "irate(node_vmstat_pginodesteal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgindesteal - Pages reclaimed via inode freeing"
      }
     ]
    },
    {
     "title": "Memory Calls Reclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "short", "label": "Calls" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pageoutrun{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pageoutrun - Kswapd calls to page reclaim"
      },
      {
       "expr": "irate(node_vmstat_allocstall{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Allocstall - Direct reclaim calls"
      },
      {
       "expr": "irate(node_vmstat_zone_reclaim_failed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Zone_reclaim_failed - Zone reclaim failures"
      }
     ]
    },
    {
     "title": "Memory Page Allocation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgalloc_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_dma - Dma mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_dma32 - Dma32 mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_movable - Movable mem page allocations"
      },
      {
       "expr": "irate(node_vmstat_pgalloc_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgalloc_normal - Normal mem page allocations"
      }
     ]
    },
    {
     "title": "Memory Page Refill",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
     "yaxes": [
      { "format": "short", "label": "Pages" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgrefill_dma{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_dma - Dma mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_dma32{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_dma32 - Dma32 mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_movable{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_movable - Movable mem pages inspected in refill_inactive_zone"
      },
      {
       "expr": "irate(node_vmstat_pgrefill_normal{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Pgrefill_normal - Normal mem pages inspected in refill_inactive_zone"
      }
     ]
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Entropy" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "Descriptors" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Processes" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "rate(node_forks{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Processes resident memory size in bytes"
      }
     ]
    },
    {
     "title": "Time Variation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_time{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Of reported time"
      },
      {
       "expr": "irate(process_start_time_seconds{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "Of the process since unix epoch in seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk R/W Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms", "label": "Millisec. read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_ms{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Read time ms"
      },
      {
       "expr": "irate(node_disk_write_time_ms{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Write time ms"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_bytes_read{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Bytes read"
      },
      {
       "expr": "irate(node_disk_bytes_written{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Bytes written"
      }
     ]
    },
    {
     "title": "Disk IOs Completed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Sectors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Sectors read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_sectors_read{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Sectors read"
      },
      {
       "expr": "irate(node_disk_sectors_written{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Sectors written"
      }
     ]
    },
    {
     "title": "Open Error File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "node_textfile_scrape_error{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Textfile scrape error (1 = true)"
      }
     ]
    },
    {
     "title": "Disk IOs Current in Progress",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "iops", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - IO now"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}- Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}- Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}- File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short", "label": "Read Only" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{ '{{' }}mountpoint{{ '}}' }}- ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Network traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Receive compressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{ '{{' }}device{{ '}}' }} - Transmit compressed"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_InReceives{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InReceives - Ip inreceives"
      },
      {
       "expr": "irate(node_netstat_Ip_InDelivers{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InDelivers - Ip indelivers"
      },
      {
       "expr": "irate(node_netstat_Ip_OutRequests{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutRequests - Ip outrequests"
      }
     ]
    },
    {
     "title": "Netstat IP In / Out Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "short", "label": "Octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP Errors / Discards",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_InDiscards{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InDiscards - Ip indiscards"
      },
      {
       "expr": "irate(node_netstat_Ip_InHdrErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InHdrErrors - Ip inhdrerrors"
      },
      {
       "expr": "irate(node_netstat_Ip_InUnknownProtos{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InUnknownProtos - Ip inunknownprotos"
      },
      {
       "expr": "irate(node_netstat_Ip_OutDiscards{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutDiscards - Ip outdiscards"
      },
      {
       "expr": "irate(node_netstat_Ip_OutNoRoutes{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "OutNoRoutes - Ip outnoroutes"
      },
      {
       "expr": "irate(node_netstat_IpExt_InNoRoutes{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InNoRoutes - IP datagrams discarded due to no routes in forwarding path"
      },
      {
       "expr": "irate(node_netstat_IpExt_InCsumErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InCsumErrors - IP datagrams with checksum errors"
      },
      {
       "expr": "irate(node_netstat_IpExt_InTruncatedPkts{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InTruncatedPkts - IP datagrams discarded due to frame not carrying enough data"
      },
      {
       "expr": "irate(node_netstat_Ip_InAddrErrors{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "InAddrErrors - Ip inaddrerrors"
      }
     ]
    }
   ]
  }
 ]
}