{
 "title": "{{ meta.namespace }} / 3scale Backend Storage Twemproxy",
 "tags": [
  "3scale",
  "backend",
  "storage",
  "twemproxy"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "role",
    "query": "label_values(twemproxy_exporter_client_err_total,attributes)"
   },
   {
    "name": "pool",
    "query": "label_values(twemproxy_exporter_client_err_total,pool)"
   }
  ]
 },
 "panels": [
  {
   "title": "Twemproxy request / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Boxy Client Errors / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(twemproxy_exporter_client_err_total{attributes=\"[[role]]\", pool=\"[[pool]]\"}[1m])",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_client_err_total{attributes=\"[[role]]\", pool=\"[[pool]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Boxy Forward Errors / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(twemproxy_exporter_forward_errors_total{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m])",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_forward_errors_total{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Out queue per shard / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_outgoing_queue{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_outgoing_queue{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "In queue per shard / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_incoming_queue{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_incoming_queue{attributes=\"[[role]]\",pool=\"[[pool]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Shard timedout / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_timeouts_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_timeouts_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Shard Error / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_err_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_err_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Shard Eof / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_eof_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m])) by (server)",
     "legendFormat": "{{ '{{' }} server {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_eof_total{pool=\"[[pool]]\",attributes=\"[[role]]\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Instances CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(100 - (avg(irate(node_cpu{instance=~\".*[[role]].*\",mode=\"idle\"}[5m])) BY (instance) * 100))",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    },
    {
     "expr": "sum((100 - (avg(irate(node_cpu{instance=~\".*[[role]].*\",mode=\"idle\"}[5m])) BY (instance) * 100)))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Twemproxy restarts (24h)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(boxy_twemproxy_restarts{attributes=\"[[role]]\"}[24h])",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  }
 ]
}