{
 "title": "{{ meta.namespace }} / 3scale Backend Storage Main",
 "tags": [
  "3scale",
  "backend",
  "storage",
  "main"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Masters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_instance_info{instance=~\".*bck-storage.*\",role=\"master\", redis_mode=\"standalone\"}",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Boxy-master unbalanced (cpu usage)?",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - min(rate(node_cpu{instance=~\".*boxy-master.*\",mode=\"idle\"}[10m])) BY (instance, job)) * 100",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Instances memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemTotal{instance=~\".*bck-storage.*\"} - node_memory_MemFree{instance=~\".*bck-storage.*\"} - node_memory_Cached{instance=~\".*bck-storage.*\"}) / (node_memory_MemTotal{instance=~\".*bck-storage.*\"}) * 100))",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Redis cmd/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(redis_commands_processed_total{ instance=~\".*bck-storage.*\"}[1m]) and ON  (instance) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(redis_memory_used_bytes{instance=~\".*bck-storage.*\"} /(1024*1024*1024)) and ON  (instance) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Number of connected clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\".*bck-storage.*\"}  and ON  (instance) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Number of keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (redis_db_keys{instance=~\".*bck-storage.*\"}) by (instance))  and ON  (instance) redis_instance_info{role=\"master\"}",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Boxy cmd/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{pool=\"backend\",attributes=\"boxy-master\"}[1m])) by (instance)",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{pool=\"backend\",attributes=\"boxy-master\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Slaves Boxies cmd/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{pool=\"backend\",attributes=\"boxy-slave\"}[1m])) by (instance)",
     "legendFormat": "{{ '{{' }} instance {{ '}}' }}"
    },
    {
     "expr": "sum(rate(twemproxy_exporter_server_requests_total{pool=\"backend\",attributes=\"boxy-slave\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Boxy Server errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_server_err_total{}[1m])) by (attributes)",
     "legendFormat": "{{ '{{' }} attributes {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Boxy Client errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(twemproxy_exporter_client_err_total{}[1m])) by (attributes)",
     "legendFormat": "{{ '{{' }} attributes {{ '}}' }}"
    }
   ]
  }
 ]
}