{
 "title": "{{ meta.namespace }} / 3scale Backend",
 "tags": [
  "3scale",
  "backend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "{{ meta.namespace }}" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_pod_info{namespace='$namespace',pod=~'backend-.*'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Listeners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Listener requests per second (by request type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",request_type=\"authorize\"}[1m]))",
     "legendFormat": "authorize"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",request_type=\"authrep\"}[1m]))",
     "legendFormat": "authrep"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",request_type=\"report\"}[1m]))",
     "legendFormat": "report"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",request_type=\"authorize_oauth\"}[1m]))",
     "legendFormat": "authorize_oauth"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",request_type=\"authrep_oauth\"}[1m]))",
     "legendFormat": "authrep_oauth"
    }
   ]
  },
  {
   "title": "Listener requests per second (by response code)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",resp_code=\"2xx\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",resp_code=\"403\"}[1m]))",
     "legendFormat": "403"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",resp_code=\"404\"}[1m]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",resp_code=\"409\"}[1m]))",
     "legendFormat": "409"
    },
    {
     "expr": "sum(rate(apisonator_listener_response_codes{namespace=\"$namespace\",resp_code=\"5xx\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Authorize requests per second (by response time bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authorize\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authorize requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authorize\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authrep requests per second (by response time bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authrep\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authrep requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authrep\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Report requests per second (by response time bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"report\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Report requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"report\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authorize (oauth) requests per second (by response time bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authorize_oauth\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authorize (oauth) requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authorize_oauth\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authrep (oauth) requests per second (by response time bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authrep_oauth\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Authrep (oauth) requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_listener_response_times_seconds_bucket{namespace=\"$namespace\",request_type=\"authrep_oauth\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Jobs per second (by job type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_worker_job_count{namespace=\"$namespace\"} [1m])) by (type)",
     "legendFormat": "{{ '{{' }} type {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Report jobs per second (by runtime bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_worker_job_runtime_seconds_bucket{namespace=\"$namespace\",type=\"ReportJob\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Report jobs per second heatmap (by runtime bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_worker_job_runtime_seconds_bucket{namespace=\"$namespace\",type=\"ReportJob\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Notify jobs per second (by runtime bucket in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apisonator_worker_job_runtime_seconds_bucket{namespace=\"$namespace\",type=\"NotifyJob\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Notify jobs per second heatmap (by runtime bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(apisonator_worker_job_runtime_seconds_bucket{namespace=\"$namespace\",type=\"NotifyJob\"}[1m])) by (le)",
     "legendFormat": "{{ '{{' }} le {{ '}}' }}"
    }
   ]
  },
  { "title": "Pods ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }, "repeat": "deployment" },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 75 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 75 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 75 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 75 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-total-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-avail-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 }, "repeat": "deployment" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }, "repeat": "deployment" },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 }, "repeat": "deployment" },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "Memory Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }, "repeat": "deployment" },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }, "repeat": "deployment" },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  }
 ]
}