apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: backend-redis
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
spec:
  name: backend-redis
  type: Opaque
  keysMap:
    REDIS_QUEUES_SENTINEL_HOSTS:
      path: {{ secret.redis_vault_path }}
      key: REDIS_QUEUES_SENTINEL_HOSTS
    REDIS_QUEUES_SENTINEL_ROLE:
      path: {{ secret.redis_vault_path }}
      key: REDIS_QUEUES_SENTINEL_ROLE
    REDIS_QUEUES_URL:
      path: {{ secret.redis_vault_path }}
      key: REDIS_QUEUES_URL
    REDIS_STORAGE_SENTINEL_HOSTS:
      path: {{ secret.redis_vault_path }}
      key: REDIS_STORAGE_SENTINEL_HOSTS
    REDIS_STORAGE_SENTINEL_ROLE:
      path: {{ secret.redis_vault_path }}
      key: REDIS_STORAGE_SENTINEL_ROLE
    REDIS_STORAGE_URL:
      path: {{ secret.redis_vault_path }}
      key: REDIS_STORAGE_URL