apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: backend-listener
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: listener
spec:
{% if listener.pdb.min_available is not defined %}
  maxUnavailable: {{ listener.pdb.max_unavailable | default(listener_pdb_max_unavailable) }}
{% endif %}
{% if listener.pdb.min_available is defined %}
  minAvailable: {{ listener.pdb.min_available }}
{% endif %}
  selector:
    matchLabels:
      deployment: backend-listener
