{
 "title": "{{ meta.namespace }} / 3scale Backend Storage Redis",
 "description": "Dashboard for Redis Statistics",
 "tags": [
  "3scale",
  "backend",
  "storage",
  "redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(redis_connected_clients{attributes=~\"storage|boxy.*\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_instance_info {instance=\"$instance\"}",
     "legendFormat": "{{ '{{' }} redis_version {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=\"$instance\"}  / redis_memory_max_bytes{instance=\"$instance\"} )"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redis mode?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_instance_info{instance=~\"$instance\"}",
     "legendFormat": "{{ '{{' }} redis_mode {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Is master?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_instance_info{instance=~\"$instance\",role=\"master\"}"
    }
   ]
  },
  {
   "title": "Is slave?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_instance_info{instance=~\"$instance\",role=\"slave\"}"
    }
   ]
  },
  {
   "title": "Slaves connected?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=~\"$instance\"}",
     "legendFormat": "slaves"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"} ",
     "legendFormat": "clients"
    },
    {
     "expr": "redis_blocked_clients{instance=\"$instance\"} ",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{instance=\"$instance\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Number of keys per DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$instance\"}) by (db)",
     "legendFormat": "{{ '{{' }} db {{ '}}' }} "
    }
   ]
  },
  {
   "title": "Total Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "cmd/s"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_command_call_duration_seconds_count{instance=\"$instance\"}[$interval])) by (cmd)",
     "legendFormat": "{{ '{{' }} cmd {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_command_call_duration_seconds_sum{instance=\"$instance\"}[$interval])) by (cmd) / sum(irate(redis_command_call_duration_seconds_count{instance=\"$instance\"}[$interval])) by (cmd)",
     "legendFormat": "{{ '{{' }} cmd {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_command_call_duration_seconds_sum{instance=\"$instance\"}[$interval])) by (cmd)",
     "legendFormat": "{{ '{{' }} cmd {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ '{{' }} input {{ '}}' }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ '{{' }} output {{ '}}' }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$instance\"}) - sum (redis_db_keys_expiring{instance=\"$instance\"})",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=\"$instance\"})",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}