apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-worker
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: worker
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app: 3scale-api-management
      threescale_component: backend
      threescale_component_element: worker
