apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-worker
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-worker
  minReplicas: {{ worker.hpa.min_replicas | default(worker_hpa_min_replicas) }}
  maxReplicas: {{ worker.hpa.max_replicas | default(worker_hpa_max_replicas) }}
  metrics:
  - type: Resource
    resource:
      name: "{{ worker.hpa.resource_name | default(worker_hpa_resource_name) }}"
      target:
        type: Utilization
        averageUtilization: {{ worker.hpa.resource_utilization | default(worker_hpa_resource_utilization) }}
