apiVersion: v1
kind: Service
metadata:
  name: backend-listener-internal
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: backend
    threescale_component_element: listener
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-internal
  selector:
    deployment: backend-listener
  type: ClusterIP
