apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cors-proxy
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: cors-proxy
    part-of: 3scale-saas
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      deployment: cors-proxy
