apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: cors-proxy
  namespace: "{{ meta.namespace }}"
  labels:
    app: cors-proxy
    part-of: 3scale-saas
spec:
{% if pdb.min_available is not defined %}
  maxUnavailable: {{ pdb.max_unavailable | default(pdb_max_unavailable) }}
{% endif %}
{% if pdb.min_available is defined %}
  minAvailable: {{ pdb.min_available }}
{% endif %}
  selector:
    matchLabels:
      deployment: cors-proxy