{
 "title": "{{ ansible_operator_meta.namespace }} / 3scale System CORS Proxy",
 "tags": [
  "3scale",
  "system",
  "cors-proxy"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "{{ ansible_operator_meta.namespace }}"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace='$namespace',pod=~'cors-proxy-.*'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "errors / min (${pod})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_error_log{namespace='$namespace',pod=~'$pod'}[1m])",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}: {{ '{{' }}level{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Total cors-proxy errors (last hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'cors-proxy-.*'}[1h]))"
    }
   ]
  },
  {
   "title": "Pods connected to DB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "sum(cors_proxy_database_connection{namespace='$namespace',})  / count(kube_pod_info{namespace='$namespace',pod=~'cors-proxy.*'}) * 100"
    }
   ]
  },
  {
   "title": "Total cors-proxy errors (last 6h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'cors-proxy-.*'}[6h]))"
    }
   ]
  },
  {
   "title": "Total cors-proxy errors (last 12h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'cors-proxy-.*'}[12h]))"
    }
   ]
  },
  {
   "title": "Total cors-proxy errors (last 24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'cors-proxy-.*'}[24h]))"
    }
   ]
  },
  {
   "title": "HTTP connections (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'cors-proxy-.*'}[1m])) by (state)",
     "legendFormat": "{{ '{{' }}state{{ '}}' }}"
    }
   ]
  },
  {
   "title": "HTTP connections (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'$pod'}[1m])) by (pod,state)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}: {{ '{{' }}state{{ '}}' }}"
    }
   ]
  },
  {
   "title": "HTTP status codes (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cors_proxy_status{namespace=\"$namespace\", pod=~'cors-proxy-.*'}[1m])) by (status)",
     "legendFormat": "{{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "HTTP status codes (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cors_proxy_status{namespace=\"$namespace\", pod=~'$pod'}[1m])) by (pod,status)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}: {{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Upstream status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(upstream_status{namespace=\"$namespace\", pod=~'cors-proxy-.*', status=~\"5.*\"}[1m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace=\"$namespace\", pod=~'cors-proxy-.*', status=~\"4.*\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace=\"$namespace\", pod=~'cors-proxy-.*', status=~\"3.*\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(upstream_status{namespace=\"$namespace\", pod=~'cors-proxy-.*', status=~\"2.*\"}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'cors-proxy.*'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'cors-proxy.*'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'cors-proxy-.*'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'cors-proxy-.*'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'cors-proxy.*'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-total-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'cors-proxy.*'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-avail-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'cors-proxy.*'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'cors-proxy-.*'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'cors-proxy-.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*', container!=''}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'cors-proxy-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace', pod=~'cors-proxy-.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace', pod=~'cors-proxy-.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  }
 ]
}