---
apiVersion: v1
kind: Service
metadata:
  name: cors-proxy
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: cors-proxy
    part-of: 3scale-saas
spec:
  selector:
    deployment: cors-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
