apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3scale-saas
resources:
- ../default

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value: { "name": "WATCH_NAMESPACE", "value": "3scale-saas" }
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value: { "name": "LOG_LEVEL", "value": "debug" }
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value: { "name": "LOG_MODE", "value": "dev" }
      - op: replace
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: "Always"
