apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/3scale/saas-operator
  newTag: v0.8.1
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: saas-operator-manager
  target:
    kind: Deployment
    labelSelector: control-plane=controller-manager
patchesStrategicMerge:
- patches/manager.resources.yaml
- patches/manager.imagePullPolicy.yaml
- patches/manager.probes.yaml
- patches/manager.env.yaml
resources:
- bases/manager.yaml
- bases/saas-operator.serviceaccount.yaml
