apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: system-memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/name: system-memcached
    spec:
      containers:
        - image: 'memcached:1.5.22'
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            tcpSocket:
              port: 11211
          name: memcached
          ports:
            - containerPort: 11211
              name: memcached
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: system-memcached
spec:
  ports:
    - name: memcached
      port: 11211
      protocol: TCP
      targetPort: memcached
  selector:
    app.kubernetes.io/name: system-memcached
  type: ClusterIP
