apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: zyncs.saas.3scale.net
spec:
  group: saas.3scale.net
  names:
    kind: Zync
    listKind: ZyncList
    plural: zyncs
    singular: zync
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Zync is the Schema for the zyncs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec defines the desired state of Zync
          properties:
            grafanaDashboard:
              properties:
                label:
                  properties:
                    key:
                      description: Label key used by grafana-operator for dashboard discovery
                      type: string
                    value:
                      description: Label value used by grafana-operator for dashboard discovery
                      type: string
                  type: object
              type: object
            image:
              properties:
                name:
                  description: Image name (docker repository)
                  type: string
                pullSecretName:
                  description: Quay pull secret for private repository
                  type: string
                tag:
                  description: Image tag
                  type: string
              type: object
            que:
              properties:
                env:
                  properties:
                    railsEnv:
                      description: Rails environment for zync
                      type: string
                  type: object
                hpa:
                  properties:
                    enabled:
                      description: Enable (true) or disable (false) HoritzontalPodAutoscaler
                      type: boolean
                    maxReplicas:
                      description: Maximum number of replicas
                      type: integer
                    minReplicas:
                      description: Minimum number of replicas
                      type: integer
                    resourceName:
                      description: Resource used for autoscale (cpu/memory)
                      enum:
                      - cpu
                      - memory
                      type: string
                    resourceUtilization:
                      description: Percentage usage of the resource used for autoscale
                      type: integer
                  type: object
                livenessProbe:
                  properties:
                    failureThreshold:
                      description: Override liveness probe failure threshold
                      type: integer
                    periodSeconds:
                      description: Override liveness probe period (seconds)
                      type: integer
                    successThreshold:
                      description: Override liveness probe success threshold
                      type: integer
                    timeoutSeconds:
                      description: Override liveness probe timeout (seconds)
                      type: integer
                  type: object
                pdb:
                  properties:
                    enabled:
                      description: Enable (true) or disable (false) PodDisruptionBudget
                      type: boolean
                    maxUnavailable:
                      description: Maximum number of unavailable pods (number or percentage of pods)
                      pattern: ^[0-9]+%?$
                      type: string
                    minAvailable:
                      description: Minimum number of available pods (number or percentage of pods), overrides maxUnavailable
                      pattern: ^[0-9]+%?$
                      type: string
                  type: object
                readinessProbe:
                  properties:
                    failureThreshold:
                      description: Override readiness probe failure threshold
                      type: integer
                    periodSeconds:
                      description: Override readiness probe period (seconds)
                      type: integer
                    successThreshold:
                      description: Override readiness probe success threshold
                      type: integer
                    timeoutSeconds:
                      description: Override readiness probe timeout (seconds)
                      type: integer
                  type: object
                replicas:
                  description: Number of replicas (ignored if hpa is enabled)
                  type: integer
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          description: Override CPU limits
                          pattern: '[0-9]+m?$'
                          type: string
                        memory:
                          description: Override Memory limits
                          pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          description: Override CPU requests
                          pattern: '[0-9]+m?$'
                          type: string
                        memory:
                          description: Override Memory requests
                          pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
                          type: string
                      type: object
                  type: object
              type: object
            secret:
              properties:
                vaultPath:
                  description: Vault Path with zync database secret definition
                  type: string
              required:
              - vaultPath
              type: object
            zync:
              properties:
                env:
                  properties:
                    railsEnv:
                      description: Rails environment for zync
                      type: string
                  type: object
                hpa:
                  properties:
                    enabled:
                      description: Enable (true) or disable (false) HoritzontalPodAutoscaler
                      type: boolean
                    maxReplicas:
                      description: Maximum number of replicas
                      type: integer
                    minReplicas:
                      description: Minimum number of replicas
                      type: integer
                    resourceName:
                      description: Resource used for autoscale (cpu/memory)
                      enum:
                      - cpu
                      - memory
                      type: string
                    resourceUtilization:
                      description: Percentage usage of the resource used for autoscale
                      type: integer
                  type: object
                livenessProbe:
                  properties:
                    failureThreshold:
                      description: Override liveness probe failure threshold
                      type: integer
                    periodSeconds:
                      description: Override liveness probe period (seconds)
                      type: integer
                    successThreshold:
                      description: Override liveness probe success threshold
                      type: integer
                    timeoutSeconds:
                      description: Override liveness probe timeout (seconds)
                      type: integer
                  type: object
                pdb:
                  properties:
                    enabled:
                      description: Enable (true) or disable (false) PodDisruptionBudget
                      type: boolean
                    maxUnavailable:
                      description: Maximum number of unavailable pods (number or percentage of pods)
                      pattern: ^[0-9]+%?$
                      type: string
                    minAvailable:
                      description: Minimum number of available pods (number or percentage of pods), overrides maxUnavailable
                      pattern: ^[0-9]+%?$
                      type: string
                  type: object
                readinessProbe:
                  properties:
                    failureThreshold:
                      description: Override readiness probe failure threshold
                      type: integer
                    periodSeconds:
                      description: Override readiness probe period (seconds)
                      type: integer
                    successThreshold:
                      description: Override readiness probe success threshold
                      type: integer
                    timeoutSeconds:
                      description: Override readiness probe timeout (seconds)
                      type: integer
                  type: object
                replicas:
                  description: Number of replicas (ignored if hpa is enabled)
                  type: integer
                resources:
                  properties:
                    limits:
                      properties:
                        cpu:
                          description: Override CPU limits
                          pattern: '[0-9]+m?$'
                          type: string
                        memory:
                          description: Override Memory limits
                          pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
                          type: string
                      type: object
                    requests:
                      properties:
                        cpu:
                          description: Override CPU requests
                          pattern: '[0-9]+m?$'
                          type: string
                        memory:
                          description: Override Memory requests
                          pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
                          type: string
                      type: object
                  type: object
              type: object
          required:
          - secret
          type: object
          x-kubernetes-preserve-unknown-fields: true
        status:
          description: Status defines the observed state of Zync
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
