apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: saas-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: saas-operator-manager-role
subjects:
- kind: ServiceAccount
  name: saas-operator-manager
  namespace: system
