---

- name: Manage cors-proxy-system-database SecretDefinition for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-system-database-secretdefinition.yaml') }}"

- name: Convert pdb.enabled boolean var into ansible pdb_state state var for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  set_fact:
    pdb_state: "absent"
  when: pdb.enabled is defined and pdb.enabled|bool == false

- name: Manage cors-proxy PodDisruptionBudget for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    state: "{{ pdb_state }}"
    definition: "{{ lookup('template', 'cors-proxy-pdb.yaml') }}"

- name: Convert hpa.enabled boolean var into ansible hpa_state state var for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  set_fact:
    hpa_state: "absent"
  when: hpa.enabled is defined and hpa.enabled|bool == false

- name: Manage cors-proxy HoritzontalPodAutoscaler for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    state: "{{ hpa_state }}"
    definition: "{{ lookup('template', 'cors-proxy-hpa.yaml') }}"
- name: Manage cors-proxy Deployment for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-deployment.yaml') }}"

- name: Manage cors-proxy Service for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-service.yaml') }}"

- name: Manage cors-proxy Ingress for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-ingress.yaml') }}"

- name: Manage cors-proxy PodMonitor for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-podmonitor.yaml') }}"

- name: Manage cors-proxy GrafanaDashboard for CORSProxy {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'cors-proxy-grafanadashboard.yaml') }}"
