apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - discoveryservice.yaml
  - configuration.yaml
  - secrets
  - apicast.yaml
  - mappingservice.yaml
  - autossl.yaml
  - backend.yaml
  - corsproxy.yaml
  - echoapi.yaml
  - zync.yaml
  - system.yaml
  - mt-ingress.yaml

secretGenerator:
  - name: system-config
    files:
      - system-config/amazon_s3.yml
      - system-config/backend.yml
      - system-config/backend_redis.yml
      # - system-config/banned_domains.yml
      - system-config/cache_store.yml
      - system-config/core.yml
      - system-config/cors.yml
      - system-config/currencies.yml
      - system-config/database.yml
      - system-config/features.yml
      # - system-config/internal_domains.yml
      - system-config/oauth2.yml
      - system-config/paperclip.yml
      # - system-config/plan_rules.yml
      - system-config/redhat_customer_portal.yml
      - system-config/redis.yml
      # - system-config/rolling_updates.yml
      - system-config/sandbox_proxy.yml
      - system-config/secrets.yml
      - system-config/segment.yml
      - system-config/service_discovery.yml
      - system-config/settings.yml
      - system-config/sidekiq_schedule.yml
      - system-config/smtp.yml
      - system-config/web_hooks.yml
      - system-config/zync.yml
    options:
      disableNameSuffixHash: true
      labels:
        threescale_component_element: config

replacements:
  - path: replacements/images.yaml
