apiVersion: saas.3scale.net/v1alpha1
kind: System
metadata:
  name: system
spec:
  image:
    name: REPLACE
    tag: REPLACE
    pullSecretName: pull-secrets
    pullPolicy: Always
  config:
    configFilesSecret: system-config
    threescaleSuperdomain: system-172-27-27-105.nip.io
    rails:
      console: true
      environment: production
      logLevel: info
    redis:
      queuesDSN: "redis://system-redis:6379"
    backend:
      externalEndpoint: "http://backend-172-27-27-100.nip.io"
      internalAPIPassword:
        override: backend-internal-api-password
      internalAPIUser:
        override: backend-internal-api-user
      internalEndpoint: "http://backend-listener-internal"
      redisDSN: "redis://backend-redis:6379/0"
    assets:
      bucket: system-assets # check config/amazon_s3.yml for the specific minio configuration (https://github.com/3scale/porta/blob/master/openshift/system/config/amazon_s3.yml)
      region: us-east-1
      accessKey:
        override: admin
      secretKey:
        override: admin123
      s3Endpoint: http://minio.minio.svc.cluster.local:9000
    databaseDSN:
      override: mysql2://app:password@system-mysql/system_enterprise
    databaseSecret:
      override: databasesecret
    secretKeyBase:
      override: 7f3b35479601a66da53071175c4833c888c2630fcafa496dc4046d143ea38666e075116bb4bac3c287b6e5d925815d5958c361786f89dc4211f6ca713ef3487e
    eventsSharedSecret:
      override: system-events-shared-secret
    searchServer:
      host: system-searchd
    zync:
      authToken:
        override: zync-auth-token
      endpoint: "http://zync:8080"
    smtp:
      address: smtp.sendgrid.net
      authProtocol: plain
      opensslVerifyMode: peer
      password:
        override: ""
      port: 587
      starttls: true
      starttlsAuto: false
      user:
        override: ""
    github:
      clientID:
        override: ""
      clientSecret:
        override: ""
    mappingServiceAccessToken:
      override: apicast-mtoken
    memcachedServers: system-memcached:11211
    recaptcha:
      privateKey:
        override: ""
      publicKey:
        override: ""
    redhatCustomerPortal:
      clientID:
        override: ""
      clientSecret:
        override: ""
      realm: ""
    segment:
      deletionToken:
        override: ""
      deletionWorkspace: ""
      writeKey:
        override: ""
  app:
    hpa: {}
    pdb: {}
    replicas: 1
  console: {}
  searchd:
    enabled: true
    image:
      name: REPLACE
      tag: REPLACE
      pullSecretName: pull-secrets
      pullPolicy: Always
    config:
      databaseStorageSize: 1Gi
  sidekiqBilling:
    config:
      maxThreads: 5
    hpa: {}
    pdb: {}
    resources: {}
    replicas: 1
  sidekiqDefault:
    config:
      maxThreads: 5
    hpa: {}
    pdb: {}
    resources: {}
    replicas: 1
  sidekiqLow:
    config:
      maxThreads: 5
    hpa: {}
    pdb: {}
    resources: {}
    replicas: 1
