apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

secretGenerator:
  - name: pull-secrets
    behavior: create
    options:
      disableNameSuffixHash: true
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=pull-secrets.json
