{
 "title": "{{ meta.namespace }} / 3scale Zync",
 "tags": [
  "3scale",
  "zync"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "{{ meta.namespace }}" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(kube_pod_info{namespace='$namespace',pod=~'zync-.*'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Zync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zync requests per second (by status)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m])) by (status)",
     "legendFormat": "{{ '{{' }}status{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Zync requests per second (by controller)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m])) by (controller)",
     "legendFormat": "{{ '{{' }}controller{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Zync 2xx requests per second (by controller)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',status=~'2[0-9]*'}[1m])) by (controller)",
     "legendFormat": "{{ '{{' }}controller{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Zync 4xx requests per second (by controller)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',status=~'4[0-9]*'}[1m])) by (controller)",
     "legendFormat": "{{ '{{' }}controller{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Zync 5xx requests per second (by controller)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',status=~'5[0-9]*'}[1m])) by (controller)",
     "legendFormat": "{{ '{{' }}controller{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m])) / sum(rate(rails_request_duration_seconds_count{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m])) / sum(rate(rails_db_runtime_seconds_count{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m])) / sum(rate(rails_view_runtime_seconds_count{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+'}[1m]))",
     "legendFormat": "View"
    }
   ]
  },
  {
   "title": "Requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_bucket{namespace='$namespace',pod=~'zync-.*'}[1m])) by (le)",
     "legendFormat": "{{ '{{' }}le{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Notifications requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_bucket{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',controller='notifications'}[1m])) by (le)",
     "legendFormat": "{{ '{{' }}le{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Tenants requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_bucket{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',controller='tenants'}[1m])) by (le)",
     "legendFormat": "{{ '{{' }}le{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Liveness requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_bucket{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',controller='status/live'}[1m])) by (le)",
     "legendFormat": "{{ '{{' }}le{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Readiness requests per second heatmap (by response time bucket in seconds)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_bucket{namespace='$namespace',pod=~'zync-[a-z0-9]+-[a-z0-9]+',controller='status/ready'}[1m])) by (le)",
     "legendFormat": "{{ '{{' }}le{{ '}}' }}"
    }
   ]
  },
  { "title": "Zync Que", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Ready Jobs count",
   "type": "graph",
   "description": "Number of jobs enqueued and ready to be executed ASAP (never failed, nor got expired).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(que_jobs_scheduled_total{namespace='$namespace',pod=~'zync-que.*',type='ready'}) by (exported_job)",
     "legendFormat": "{{ '{{' }}exported_job{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Scheduled Jobs count",
   "type": "graph",
   "description": "Number of jobs enqueued to be executed some time in the future, but not now (never failed, nor got expired).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(que_jobs_scheduled_total{namespace='$namespace',pod=~'zync-que.*',type='scheduled'}) by (exported_job)",
     "legendFormat": "{{ '{{' }}exported_job{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Failed Jobs count",
   "type": "graph",
   "description": "Number of jobs that executed successfully.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(que_jobs_scheduled_total{namespace='$namespace',pod=~'zync-que.*',type='failed'}) by (exported_job)",
     "legendFormat": "{{ '{{' }}exported_job{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Finished Jobs count",
   "type": "graph",
   "description": "Number of jobs that failed at least once, did not run out of attempts to retry and therefore are scheduled for retry any time soon.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(que_jobs_scheduled_total{namespace='$namespace',pod=~'zync-que.*',type='finished'}) by (exported_job)",
     "legendFormat": "{{ '{{' }}exported_job{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Expired Jobs count",
   "type": "graph",
   "description": "Number of jobs that failed and ran out of attempts to retry, therefore won't be retried again.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(que_jobs_scheduled_total{namespace='$namespace',pod=~'zync-que.*',type='expired'}) by (exported_job)",
     "legendFormat": "{{ '{{' }}exported_job{{ '}}' }}"
    }
   ]
  },
  { "title": "Pods ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }, "repeat": "deployment" },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m]))) by (pod)"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-total-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-avail-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'}",
     "legendFormat": "{{ '{{' }}deployment{{ '}}' }}-unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }, "repeat": "deployment" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "CPU Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }, "repeat": "deployment" },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }, "repeat": "deployment" },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  { "title": "Memory Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }, "repeat": "deployment" },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }, "repeat": "deployment" },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace',pod=~'$deployment-[a-z0-9]+-[a-z0-9]+'}[5m])) by (pod)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  }
 ]
}