apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zync-que
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: zync
    threescale_component_element: zync-que
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app: 3scale-api-management
      deployment: zync-que
