apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zync
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: zync
    threescale_component_element: zync
spec:
{% if zync.pdb.min_available is not defined %}
  maxUnavailable: {{ zync.pdb.max_unavailable | default(zync_pdb_max_unavailable) }}
{% endif %}
{% if zync.pdb.min_available is defined %}
  minAvailable: {{ zync.pdb.min_available }}
{% endif %}
  selector:
    matchLabels:
      deployment: zync