---

- name: Manage zync SecretDefinition for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-secretdefinition.yaml') }}"

- name: Manage zync-que Deployment for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-que-deployment.yaml') }}"

- name: Manage zync-que PodMonitor for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-que-podmonitor.yaml') }}"

- name: Manage zync Deployment for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-deployment.yaml') }}"

- name: Manage zync Service for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-service.yaml') }}"

- name: Manage zync PodMonitor for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-podmonitor.yaml') }}"

- name: Manage zync GrafanaDashboard for Zync {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-grafanadashboard.yaml') }}"
