---

- name: Manage zync SecretDefinition for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-secretdefinition.yaml') }}"

- name: Convert que.pdb.enabled boolean var into ansible que_pdb_state state var for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  set_fact:
    que_pdb_state: "absent"
  when: que.pdb.enabled is defined and que.pdb.enabled|bool == false

- name: Manage zync-que PodDisruptionBudget for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    state: "{{ que_pdb_state }}"
    definition: "{{ lookup('template', 'zync-que-pdb.yaml') }}"

- name: Convert que.hpa.enabled boolean var into ansible que_hpa_state state var for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  set_fact:
    que_hpa_state: "absent"
  when: que.hpa.enabled is defined and que.hpa.enabled|bool == false

- name: Manage zync-que HoritzontalPodAutoscaler for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    state: "{{ que_hpa_state }}"
    definition: "{{ lookup('template', 'zync-que-hpa.yaml') }}"

- name: Manage zync-que Deployment for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-que-deployment.yaml') }}"

- name: Manage zync-que PodMonitor for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-que-podmonitor.yaml') }}"

- name: Convert zync.pdb.enabled boolean var into ansible zync_pdb_state state var for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  set_fact:
    zync_pdb_state: "absent"
  when: zync.pdb.enabled is defined and zync.pdb.enabled|bool == false

- name: Manage zync PodDisruptionBudget for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    state: "{{ zync_pdb_state }}"
    definition: "{{ lookup('template', 'zync-pdb.yaml') }}"

- name: Convert zync.hpa.enabled boolean var into ansible zync_hpa_state state var for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  set_fact:
    zync_hpa_state: "absent"
  when: zync.hpa.enabled is defined and zync.hpa.enabled|bool == false

- name: Manage zync HoritzontalPodAutoscaler for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    state: "{{ zync_hpa_state }}"
    definition: "{{ lookup('template', 'zync-hpa.yaml') }}"

- name: Manage zync Deployment for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-deployment.yaml') }}"

- name: Manage zync Service for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-service.yaml') }}"

- name: Manage zync PodMonitor for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-podmonitor.yaml') }}"

- name: Manage zync GrafanaDashboard for Zync {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'zync-grafanadashboard.yaml') }}"
