apiVersion: v1
kind: Service
metadata:
  name: system
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: ui-api
  selector:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app