production:
  test_api_hosts:
  - echo-api-172-27-27-103.nip.io
  ignore_test_failures: []
  apicast_staging_endpoint: https://%{system_name}-%{account_id}.staging-172-27-27-102.nip.io
  apicast_production_endpoint: https://%{system_name}-%{account_id}.production-172-27-27-101.nip.io
  apicast_registry_url: http://apicast-staging-management:8090/policies
  self_managed_apicast_registry_url: http://policies.apicast.io/latest/policies.json
  backend_endpoint: <%= ENV.fetch('BACKEND_PUBLIC_URL') %>
  verify_mode: <%= ::OpenSSL::SSL::VERIFY_PEER %>
