production:
  address: <%= ENV['SMTP_ADDRESS'] %>
  port: <%= ENV.fetch('SMTP_PORT', '25').to_i %>
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  domain: <%= ENV['THREESCALE_SUPERDOMAIN'].presence || 'localhost' %>
  authentication: "<%= ENV['SMTP_AUTHENTICATION'].presence || 'plain' %>"
  enable_starttls_auto: <%= ENV['SMTP_STARTTLS_AUTO'].presence || false %>
  enable_starttls: <%= ENV['SMTP_STARTTLS'].presence || true %>
  openssl_verify_mode: "<%= ENV['SMTP_OPENSSL_VERIFY_MODE'].presence || 'none' %>"
  ca_file: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
