# APICAST
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_STAGING_DNS
  targets:
    - select:
        kind: Apicast
      fieldPaths:
        - spec.staging.endpoint.dns.0
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_PRODUCTION_DNS
  targets:
    - select:
        kind: Apicast
      fieldPaths:
        - spec.production.endpoint.dns.0

# AUTOSSL
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.config.proxyEndpoint
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.AUTOSSL_VERIFICATION_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.config.verificationEndpoint
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.AUTOSSL_DNS
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.endpoint.dns.0

# BACKEND
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_EVENTS_URL
  targets:
    - select:
        kind: Backend
      fieldPaths:
        - spec.config.systemEventsHookURL.override
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.BACKEND_DNS
  targets:
    - select:
        kind: Backend
      fieldPaths:
        - spec.listener.endpoint.dns.0

# ECHOAPI
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ECHOAPI_DNS
  targets:
    - select:
        kind: EchoAPI
      fieldPaths:
        - spec.endpoint.dns.0

# MAPPINGSERVICE
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: MappingService
      fieldPaths:
        - spec.config.apiHost

# SYSTEM
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_SUPERDOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.threescaleSuperdomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.BACKEND_EXTERNAL_ENDPOINT
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.backend.externalEndpoint
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_STAGING_DOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.stagingDomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_PRODUCTION_DOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.productionDomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_CLOUD_HOSTED_REGISTRY_URL
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.cloudHostedRegistryURL
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_SELF_MANAGED_REGISTRY_URL
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.selfManagedRegistryURL
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_DNS
  targets:
    - select:
        kind: Service
        name: mt-ingress
      fieldPaths:
        - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_DNS
  targets:
    - select:
        kind: Certificate
        name: mt-ingress-cert
      fieldPaths:
        - spec.dnsNames.0

# CERT-MANAGER
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.CERT_MANAGER_ISSUER
  targets:
    - select:
        kind: Certificate
      fieldPaths:
        - spec.issuerRef.name