# CONFIGURE APICAST ENDPOINTS
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_STAGING_DOMAIN
  targets:
    - select:
        kind: Apicast
      fieldPaths:
        - spec.staging.endpoint.dns.0
      options:
        delimiter: "."
        index: 1
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.stagingDomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_PRODUCTION_DOMAIN
  targets:
    - select:
        kind: Apicast
      fieldPaths:
        - spec.production.endpoint.dns.0
      options:
        delimiter: "."
        index: 1
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.productionDomain

# CONFIGURE AUTOSSL ENDPOINT
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.config.proxyEndpoint
        - spec.config.verificationEndpoint
      options:
        delimiter: "/"
        index: 2
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.AUTOSSL_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.endpoint.dns.0

# CONFIGURE ECHOAPI ENDPOINT
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ECHOAPI_ENDPOINT
  targets:
    - select:
        kind: EchoAPI
      fieldPaths:
        - spec.endpoint.dns.0

# CONFIGURE BACKEND ENDPOINT
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.BACKEND_ENDPOINT
  targets:
    - select:
        kind: Backend
      fieldPaths:
        - spec.listener.endpoint.dns.0
    - select:
        kind: System
      fieldPaths:
        - spec.config.backend.externalEndpoint
      options:
        delimiter: "/"
        index: 2

# CONFIGURE SYSTEM ENDPOINT
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: Backend
      fieldPaths:
        - spec.config.systemEventsHookURL.override
      options:
        delimiter: "/"
        index: 2
    - select:
        kind: MappingService
      fieldPaths:
        - spec.config.apiHost
      options:
        delimiter: "/"
        index: 2
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
    options:
      delimiter: "multitenant-admin."
      index: 1
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.threescaleSuperdomain
    - select:
        kind: Service
        name: mt-ingress
      fieldPaths:
        - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
      options:
        delimiter: "."
        index: 1
    - select:
        kind: Certificate
        name: mt-ingress-cert
      fieldPaths:
        - spec.dnsNames.0
      options:
        delimiter: "."
        index: 1

# CERT-MANAGER
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.CERT_MANAGER_ISSUER
  targets:
    - select:
        kind: Certificate
      fieldPaths:
        - spec.issuerRef.name
