# AUTOSSL
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.config.proxyEndpoint
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.AUTOSSL_VERIFICATION_ENDPOINT
  targets:
    - select:
        kind: AutoSSL
      fieldPaths:
        - spec.config.verificationEndpoint

# BACKEND
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_EVENTS_URL
  targets:
    - select:
        kind: Backend
      fieldPaths:
        - spec.config.systemEventsHookURL.override

# MAPPINGSERVICE
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_ENDPOINT
  targets:
    - select:
        kind: MappingService
      fieldPaths:
        - spec.config.apiHost

# SYSTEM
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.SYSTEM_SUPERDOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.threescaleSuperdomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.BACKEND_EXTERNAL_ENDPOINT
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.backend.externalEndpoint
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_STAGING_DOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.stagingDomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_PRODUCTION_DOMAIN
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.productionDomain
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_CLOUD_HOSTED_REGISTRY_URL
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.cloudHostedRegistryURL
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.APICAST_SELF_MANAGED_REGISTRY_URL
  targets:
    - select:
        kind: System
      fieldPaths:
        - spec.config.apicast.selfManagedRegistryURL
