# permissions for end users to edit apicasts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicast-editor-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/status
  verbs:
  - get
