# permissions for end users to view apicasts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicast-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/status
  verbs:
  - get
