# permissions for end users to view autossls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autossl-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls/status
  verbs:
  - get
