# permissions for end users to view corsproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: corsproxy-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - corsproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - corsproxies/status
  verbs:
  - get
