# permissions for end users to edit corsproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: echoapi-editor-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - echoapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - echoapis/status
  verbs:
  - get
