# permissions for end users to edit redisshards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisshard-editor-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - redisshards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - redisshards/status
  verbs:
  - get
