# permissions for end users to view redisshards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisshard-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - redisshards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - redisshards/status
  verbs:
  - get
