
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling/v2beta2
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org/v1alpha1
  resources:
  - grafanadashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com/v1
  resources:
  - podmonitors
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy/v1beta1
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls/status
  verbs:
  - get
  - patch
  - update
