
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - corsproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - corsproxies/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - corsproxies/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: placeholder
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - grafanadashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - apicasts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - autossls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - mappingservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - mappingservices/finalizers
  verbs:
  - update
- apiGroups:
  - saas.3scale.net
  resources:
  - mappingservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets-manager.tuenti.io
  resources:
  - secretdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
