# permissions for end users to view sentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentinel-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - sentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - sentinels/status
  verbs:
  - get
