# permissions for end users to edit systems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system-editor-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - systems/status
  verbs:
  - get
