# permissions for end users to edit zyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zync-editor-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - zyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - zyncs/status
  verbs:
  - get
