# permissions for end users to view zyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zync-viewer-role
rules:
- apiGroups:
  - saas.3scale.net
  resources:
  - zyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - saas.3scale.net
  resources:
  - zyncs/status
  verbs:
  - get
