apiVersion: saas.3scale.net/v1alpha1
kind: MappingService
metadata:
  name: example
spec:
  image:
    tag: mapping-service-v3.8.0-r3
  replicas: 1
  env:
    apiHost: http://system:3000
    previewBaseDomain: stg-saas.3scale.net
  secret:
    systemAdminTokenVaultPath: secret/data/openshift/stg-saas-ocp/3scale/mappingservice-system-master-access-token
