apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: echoapis.saas.3scale.net
spec:
  group: saas.3scale.net
  names:
    kind: EchoAPI
    listKind: EchoAPIList
    plural: echoapis
    singular: echoapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      description: EchoAPI is the Schema for EchoAPI instance
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          description: EchoAPISpec defines the desired state of EchoAPI
          required:
          - externalDnsHostname
          - marin3r
          properties:
            image:
              type: object
              properties:
                name:
                  type: string
                  description: Image name (docker repository)
                tag:
                  type: string
                  description: Image tag
                pullSecretName:
                  type: string
                  description: Quay pull secret for private repository
            pdb:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Enable (true) or disable (false) PodDisruptionBudget
                maxUnavailable:
                  type: string
                  pattern: "^[0-9]+%?$"
                  description: Maximum number of unavailable pods (number or percentage of pods)
                minAvailable:
                  type: string
                  pattern: "^[0-9]+%?$"
                  description: Minimum number of available pods (number or percentage of pods), overrides maxUnavailable
            hpa:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Enable (true) or disable (false) HoritzontalPodAutoscaler
                minReplicas:
                  type: integer
                  description: Minimum number of replicas
                maxReplicas:
                  type: integer
                  description: Maximum number of replicas
                resourceName:
                  type: string
                  description: Resource used for autoscale (cpu/memory)
                  enum:
                  - cpu
                  - memory
                resourceUtilization:
                  type: integer
                  description: Percentage usage of the resource used for autoscale
            replicas:
              type: integer
              description: Number of replicas (ignored if hpa is enabled)
            resources:
              type: object
              properties:
                requests:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "[0-9]+m?$"
                      description: Override CPU requests
                    memory:
                      type: string
                      pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                      description: Override Memory requests
                limits:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: "[0-9]+m?$"
                      description: Override CPU limits
                    memory:
                      type: string
                      pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                      description: Override Memory limits
            livenessProbe:
              type: object
              properties:
                initialDelaySeconds:
                  type: integer
                  description: Override liveness probe initial delay (seconds)
                timeoutSeconds:
                  type: integer
                  description: Override liveness probe timeout (seconds)
                periodSeconds:
                  type: integer
                  description: Override liveness probe period (seconds)
                successThreshold:
                  type: integer
                  description: Override liveness probe success threshold
                failureThreshold:
                  type: integer
                  description: Override liveness probe failure threshold
            readinessProbe:
              type: object
              properties:
                initialDelaySeconds:
                  type: integer
                  description: Override readiness probe initial delay (seconds)
                timeoutSeconds:
                  type: integer
                  description: Override readiness probe timeout (seconds)
                periodSeconds:
                  type: integer
                  description: Override readiness probe period (seconds)
                successThreshold:
                  type: integer
                  description: Override readiness probe success threshold
                failureThreshold:
                  type: integer
                  description: Override readiness probe failure threshold
            externalDnsHostname:
              type: string
              description: DNS hostnames to manage on AWS Route53 by external-dns
            marin3r:
              type: object
              required:
              - enabled
              properties:
                enabled:
                  type: boolean
                  description:  Enable (true) or disable (false) marin3r
                annotations:
                  additionalProperties:
                    type: string
                  description: Map of deployment annotations
                  type: object
            loadBalancer:
              type: object
              properties:
                proxyProtocol:
                  type: boolean
                  description:  Enable (true) or disable (false) proxy protocol with aws-nlb-helper-operator
                crossZoneLoadBalancingEnabled:
                  type: boolean
                  description: Enable (true) or disable (false) cross zone load balancing
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
