apiVersion: saas.3scale.net/v1alpha1
kind: Zync
metadata:
  name: simple
spec:
  secret:
    zyncDatabaseVaultPath: secret/data/openshift/stg-saas-ocp/stg-saas-3scale-zync
  zync:
    replicas: 1
    env:
      dbWaitSleepSeconds: 1