apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autossls.saas.3scale.net
spec:
  group: saas.3scale.net
  names:
    kind: AutoSSL
    listKind: AutoSSLList
    plural: autossls
    singular: autossl
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
