apiVersion: saas.3scale.net/v1alpha1
kind: Backend
metadata:
  name: example
spec:
  image:
    tag: v2.101.1
  config:
    rackEnv: example
  secret:
    redisVaultPath: secret/data/openshift/cluster-example/3scale/backend-redis
    systemEventsHookVaultPath: secret/data/openshift/cluster-example/3scale/backend-system-events-hook
    internalApiVaultPath: secret/data/openshift/cluster-example/3scale/backend-internal-api
  listener:
    routeHost: backend-example.3scale.net
    replicas: 2
  worker:
    replicas: 2
  cron:
    replicas: 1
