---

- name: "{{ 'Apply' if resource.enabled else 'Remove' }} {{ resource.manifest }} for {{ role_name }} {{ ansible_operator_meta.name }} on Namespace {{ ansible_operator_meta.namespace }}"
  k8s:
    state: "{{ 'present' if resource.enabled else 'absent' }}"
    definition: "{{ lookup('template', resource.manifest) }}"
  ignore_errors: yes