resources:
  - https://raw.githubusercontent.com/tektoncd/pipeline/release-v0.49.x/config/300-pipeline.yaml
  - https://raw.githubusercontent.com/tektoncd/pipeline/release-v0.49.x/config/300-task.yaml

patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
    patch: |-
      - op: remove
        path: /spec/conversion