apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Integration & Delivery
    containerImage: quay.io/3scale/saas-operator
    createdAt: 2020-06-02T15:49:31GMT
    description: |-
      The 3scale SaaS Operator creates and maintains a SaaS-ready deployment
      of the Red Hat 3scale API Management on OpenShift.
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    repository: https://github.com/3scale/saas-operator
    support: Red Hat
  name: saas-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: |
    The 3scale SaaS Operator creates and maintains a SaaS-ready deployment of the Red Hat 3scale API Management on OpenShift.

    ## Supported Features

    - **Installer:** A way to install a SaaS ready deployment of the 3scale API Management components, providing configurability options at the time of installation
    - **Reconcilliation:** Tunable CRD parameters for each component after 3scale API Management solution is installed

    ## Documentation

    - [Getting started](https://github.com/3scale/saas-operator/blob/master/docs/getting-started.md)
    - [Custom Resource Definitions reference](https://github.com/3scale/saas-operator/tree/master/docs/reference)
    - [Development](https://github.com/3scale/saas-operator/blob/master/docs/development.md)

    ## License

    3scale SaaS Operator is licensed under the [Apache 2.0 license](https://github.com/3scale/saas-operator/blob/master/LICENSE)
  displayName: 3scale SaaS Operator
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAYAAABpYH0BAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAABp0RVh0VGl0bGUATkdJTlhfUGFydG5lcnNfbG9nb198DJyHAAAGcklEQVRo3u2Ye2wURRzHlz4OKkiF0lqxtLfX8iiVEKwFpCIUakQRNYGSKFrAxEoEKxTYuwoIGFFATFSIGqOi8R2NCqLGJyAmRkEBFYwCEgTrI4DSu2sBwfP7a7/bDMtsW/40nV/yye3Nzs7s/ub3mrEsI0aMGDFixIgRI0baLwPAKKOGc5N88ACvD4F/qcR5bBsCio2azpYqEAY9wPVsewP8BDJAEjgffAQ2gZ4gZNRmWVeDoaASVGvui/WlgfvBz6A7SAcT2dahJUgX/VNpywZPgpGgEzgALgc2GMc+N4EyXncDY9m3w0kAvAweVNpuBwmwnkrJ1Dw3Bgzm9R3s37+jKU/iWg2vJ4HneS0uuggMomUdYPuVjIkl/L8CfEErFsvsB/qqEySWBLs0OPbQeNieEAvbt8hvgxMcLu0+Gf86cBuYBsbT6v2kknE7rR3fOpWGoZtX2kaACo53M72ra1uDpvElXWVecmxOTs9YOHh3LBIcp/RL5+8aWtoy/v+W/4uVjH3IfSg6Lz8LStsPDoJtsYj9GRS4BdeHo2F7X/3cfr2UOZ4B/4DvmaA2cfxTwNG8+2DOHaVyWpNipe8Uz70+4BdwFGxjghSjOMiwNsBv0BSwgPFrsatIfNxmkBDEWpiNF/KZLDAT5tkzGi4ogvZz8H+4MuadYHqLAsP2TFFeoqo49QyrnJOThvYD8UhwBpty+YHDNO8pHlLPCkCVh8EusBx80oYCHwXbwSrwgefeYt4LaPSzAzzmN6iY5wZwEUuTVCrwiKLAhcyyu9QHo06wuqlPxJ5rNStxL8cI0M0tjvUQ+ryjmxz3NkQj9n38O5YK1LnXpbSMbkpbEi1dLLOQSdBuxVB+50IUgdO0OldeIjpZAlb6KTBZ8fF0xi8ox56Fj2sAO+JOn94eNxAXmBxz7Kvi4eDeeDjvGo4zXnGrv1xFxOYHsxvn2nlaBcKdwXz+vYIKvPAcyq7TXDyRrxizdTKeYSCb/78Btcr9Z2lI5ySduKonwGiwWr7Jp28SFZLLuDRcyd5yrzOtz23Txoyj4VC6JJNYJFQec4KzxdLra0P9lKQlin+PAfxallB9fRLEi+BD5f8ssMenjHqV47oyG/yo9J3G2LuIibScSbK3JmycUbpEuepVdGPJQucBcbmBnhj0dnNGLQrEndBl8XvypL/EL7HAp8BG9n2dY9Z4J5R4KolDgPLqYMWrJBZ6XPVp8DnYDepAIz9uhSf0yLvfqrTJjug4KPVMKwsTZ81qKXH8pBJvO1EHb4GtYB84Qgv/TTNmi5Qw4AcUpQaoEClLxL32U0lZ9bUXZ8TCoV2MjyeRpafxOZvljsj7VODi1sy/aSEkGzuh5e3wlKkcM08pXWKemCjyJt9dFSmHjtEwVJH69vE25u7K7/m4rZOWdLroI8pLW3SRhJuB4469yE0u5GiiuW9/FuEZdOWRjIsWXHVq1Mkr000cDYeWSiJRFmF6K6VWgqHGfa+trNlU1lBZqlV/Cr7U9H2CZUsXGsgIn7lncuuqlQIG13c9Vvk3zTyXq9+VJckyjwLjiYomRa3iB06h6w9SMu16cdV2KPAGukyypms3jj+KcekUq4JtGk4whrql0WnWlbq+4saTwTqw1kdH1XRp35V9hWauvmylJ3hKsZvSGAkG8cF/tJQ4sEjez+QzAWbywpa4F7FXo+9GT6yzEncVdG6qNx3bLREKqaQJGheuZpnSm2GlzkfRFhXh1nm1LHX8EsELNJ6VPG26wHNfPHMz3bhVKVVWzXWnXp7iuClbShxE7VYRj4RKlP1wFa8dZsKx7oMNC/L7QFHbwXHZkTCB/ABiiIF7GpyCHGWelbSKY9wF/MokckqJqTtp8X5SRqsT6/vOk3y8Us4EJWebX/P6CC3uMBetrj3nnju5+pnMZo3cQmXRvCuZsXZrzv5qaMUiWzjOWcdbsqWLR/KLXaK1uQMTS0anaN4lnSGgjAxSLCOZH53ZRtIpY31Y7jEEXXk2ht9p8ZlhfK6URpPcnppwpBLAZTfyGpPCEK7mc0w26+hGy5gFvduuQtZYPTrqueBSzelDNpWaTyUncdsjlnYj+wyksju8zGAimEi3LvLEpwRdKpU7hEl07wI1cRixrAhdt4ylw1oqaDI34d2VYnSzUZf/Qat7YJrgcb7FY6N7laCealTV9nZmqKdOTDFqMWLEiBEjRowY+V/Jf9KGC5ojEk+KAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - saas
  - 3scale
  - operations
  links:
  - name: GitHub Repository
    url: https://github.com/3scale/saas-operator
  - name: 3scale
    url: https://3scale.net
  maintainers:
  - email: 3scale-operations@redhat.com
    name: 3scale Ops
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.3scale.net/
  version: 0.0.0
