---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3scale-saas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: 3scale-saas-operator
  template:
    metadata:
      labels:
        name: 3scale-saas-operator
    spec:
      serviceAccountName: 3scale-saas-operator
      containers:
        - name: 3scale-saas-operator
          image: REPLACE_IMAGE
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "3scale-saas-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
