---
apiVersion: v1
kind: Service
metadata:
  name: "apicast-{{ apicast_env }}-management"
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: "apicast-{{ apicast_env }}"
    threescale_component_element: gateway
spec:
  type: ClusterIP
  ports:
    - name: management
      protocol: TCP
      port: 8090
      targetPort: management
  selector:
    deployment: "apicast-{{ apicast_env }}"