apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-sidekiq
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: sidekiq
spec:
{% if sidekiq.hpa.enabled is defined and sidekiq.hpa.enabled == false %}
  replicas: {{ sidekiq.replicas | default(sidekiq_replicas) }}
{% endif %}
  selector:
    matchLabels:
      app: 3scale-api-management
      threescale_component: system
      threescale_component_element: sidekiq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: 3scale-api-management
        threescale_component: system
        threescale_component_element: sidekiq
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      # container > system-sidekiq
        - name: system-sidekiq
          image: "{{ image.name | default(image_name) }}:{{ image.tag | default(image_tag) }}"
          imagePullPolicy: "{{ image.pullPolicy | default(image_pull_policy) }}"
          args:
            - rake
            - sidekiq:worker
            - RAILS_MAX_THREADS=25
        ## container > system-sidekiq > ports
          ports:
            - containerPort: 9394
              name: metrics
              protocol: TCP
        ## container > system-sidekiq > resources
          resources:
            requests:
              memory: "{{ sidekiq.resources.requests.memory | default(sidekiq_resources_requests_memory) }}"
              cpu: "{{ sidekiq.resources.requests.cpu | default(sidekiq_resources_requests_cpu) }}"
            limits:
              memory: "{{ sidekiq.resources.limits.memory | default(sidekiq_resources_limits_memory) }}"
              cpu: "{{ sidekiq.resources.limits.cpu | default(sidekiq_resources_limits_cpu) }}"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9394
              scheme: HTTP
            initialDelaySeconds: {{ sidekiq.liveness_probe.initial_delay_seconds | default(sidekiq_liveness_probe_initial_delay_seconds) }}
            timeoutSeconds: {{ sidekiq.liveness_probe.timeout_seconds | default(sidekiq_liveness_probe_timeout_seconds) }}
            periodSeconds: {{ sidekiq.liveness_probe.period_seconds | default (sidekiq_liveness_probe_period_seconds) }}
            successThreshold: {{ sidekiq.liveness_probe.success_threshold | default(sidekiq_liveness_probe_success_threshold) }}
            failureThreshold: {{ sidekiq.liveness_probe.failure_threshold | default(sidekiq_liveness_probe_failure_threshold) }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9394
              scheme: HTTP
            initialDelaySeconds: {{ sidekiq.readiness_probe.initial_delay_seconds | default(sidekiq_readiness_probe_initial_delay_seconds) }}
            timeoutSeconds: {{ sidekiq.readiness_probe.timeout_seconds | default(sidekiq_readiness_probe_timeout_seconds) }}
            periodSeconds: {{ sidekiq.readiness_probe.period_seconds | default (sidekiq_readiness_probe_period_seconds) }}
            successThreshold: {{ sidekiq.readiness_probe.success_threshold | default(sidekiq_readiness_probe_success_threshold) }}
            failureThreshold: {{ sidekiq.readiness_probe.failure_threshold | default(sidekiq_readiness_probe_failure_threshold) }}
        ## container > system-sidekiq > volumeMounts
          volumeMounts:
            - mountPath: /tmp
              name: system-tmp
            - mountPath: /opt/system-extra-configs
              name: system-config
              readOnly: true
        ## container > system-sidekiq > env
          env:
            ## configmap/system-sphinx
            - name: THINKING_SPHINX_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: SPHINX_ADDRESS
                  name: system-sphinx
            - name: THINKING_SPHINX_PORT
              valueFrom:
                configMapKeyRef:
                  key: SPHINX_PORT
                  name: system-sphinx
            ## configmap/system-environment
            - name: AMP_RELEASE
              valueFrom:
                configMapKeyRef:
                  key: AMP_RELEASE
                  name: system-environment
            - name: FORCE_SSL
              valueFrom:
                configMapKeyRef:
                  key: FORCE_SSL
                  name: system-environment
            - name: PROVIDER_PLAN
              valueFrom:
                configMapKeyRef:
                  key: PROVIDER_PLAN
                  name: system-environment
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: RAILS_ENV
                  name: system-environment
            - name: RAILS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: RAILS_LOG_LEVEL
                  name: system-environment
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  key: RAILS_LOG_TO_STDOUT
                  name: system-environment
            - name: SSL_CERT_DIR
              valueFrom:
                configMapKeyRef:
                  key: SSL_CERT_DIR
                  name: system-environment
            - name: THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE
              valueFrom:
                configMapKeyRef:
                  key: THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE
                  name: system-environment
            - name: THREESCALE_SUPERDOMAIN
              valueFrom:
                configMapKeyRef:
                  key: THREESCALE_SUPERDOMAIN
                  name: system-environment
            ### secret/system-database
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: URL
                  name: system-database
            ### secret/system-seed
            - name: MASTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MASTER_ACCESS_TOKEN
                  name: system-seed
            - name: MASTER_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: MASTER_DOMAIN
                  name: system-seed
            - name: MASTER_USER
              valueFrom:
                secretKeyRef:
                  key: MASTER_USER
                  name: system-seed
            - name: MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MASTER_PASSWORD
                  name: system-seed
            - name: ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: ADMIN_ACCESS_TOKEN
                  name: system-seed
            - name: USER_LOGIN
              valueFrom:
                secretKeyRef:
                  key: ADMIN_USER
                  name: system-seed
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ADMIN_PASSWORD
                  name: system-seed
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: ADMIN_EMAIL
                  name: system-seed
            - name: TENANT_NAME
              valueFrom:
                secretKeyRef:
                  key: TENANT_NAME
                  name: system-seed
            ### secret/system-events-hook
            - name: EVENTS_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: system-events-hook
            ### secret/system-recaptcha
            - name: RECAPTCHA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: PUBLIC_KEY
                  name: system-recaptcha
            - name: RECAPTCHA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: PRIVATE_KEY
                  name: system-recaptcha
            ### secret/system-system-app
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: system-app
            - name: ACCESS_CODE
              valueFrom:
                secretKeyRef:
                  key: ACCESS_CODE
                  name: system-app
            - name: SEGMENT_DELETION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: SEGMENT_DELETION_TOKEN
                  name: system-app
            - name: SEGMENT_DELETION_WORKSPACE
              valueFrom:
                secretKeyRef:
                  key: SEGMENT_DELETION_WORKSPACE
                  name: system-app
            - name: NEWRELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: NEWRELIC_LICENSE_KEY
                  name: system-app
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GITHUB_CLIENT_ID
                  name: system-app
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GITHUB_CLIENT_SECRET
                  name: system-app
            - name: PROMETHEUS_USER
              valueFrom:
                secretKeyRef:
                  key: PROMETHEUS_USER
                  name: system-app
            - name: PROMETHEUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PROMETHEUS_PASSWORD
                  name: system-app
            - name: RH_CUSTOMER_PORTAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: RH_CUSTOMER_PORTAL_CLIENT_ID
                  name: system-app
            - name: RH_CUSTOMER_PORTAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: RH_CUSTOMER_PORTAL_CLIENT_SECRET
                  name: system-app
            - name: SEGMENT_WRITE_KEY
              valueFrom:
                secretKeyRef:
                  key: SEGMENT_WRITE_KEY
                  name: system-app
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  key: BUGSNAG_API_KEY
                  name: system-app
            - name: DB_SECRET
              valueFrom:
                secretKeyRef:
                  key: DB_SECRET
                  name: system-app
            ### secret/system-memcached
            - name: MEMCACHE_SERVERS
              valueFrom:
                secretKeyRef:
                  key: SERVERS
                  name: system-memcached
            ### secret/system-redis
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: URL
                  name: system-redis
            - name: MESSAGE_BUS_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: MESSAGE_BUS_URL
                  name: system-redis
            - name: ACTION_CABLE_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: ACTION_CABLE_REDIS_URL
                  name: system-redis
            - name: REDIS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  key: NAMESPACE
                  name: system-redis
            - name: MESSAGE_BUS_REDIS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  key: MESSAGE_BUS_NAMESPACE
                  name: system-redis
            - name: REDIS_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: SENTINEL_HOSTS
                  name: system-redis
            - name: REDIS_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: SENTINEL_ROLE
                  name: system-redis
            - name: MESSAGE_BUS_REDIS_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: MESSAGE_BUS_SENTINEL_HOSTS
                  name: system-redis
            - name: MESSAGE_BUS_REDIS_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: MESSAGE_BUS_SENTINEL_ROLE
                  name: system-redis
            ### secret/system-smtp
            - name: SMTP_ADDRESS
              valueFrom:
                secretKeyRef:
                  key: address
                  name: system-smtp
            - name: SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: system-smtp
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: system-smtp
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: system-smtp
            - name: SMTP_AUTHENTICATION
              valueFrom:
                secretKeyRef:
                  key: authentication
                  name: system-smtp
            - name: SMTP_OPENSSL_VERIFY_MODE
              valueFrom:
                secretKeyRef:
                  key: openssl_verify_mode
                  name: system-smtp
            - name: SMTP_STARTTLS_AUTO
              valueFrom:
                secretKeyRef:
                  key: enable_starttls_auto
                  name: system-smtp
            ### secret/system-master-apicast
            - name: APICAST_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: ACCESS_TOKEN
                  name: system-master-apicast
            ### secret/zync
            - name: ZYNC_AUTHENTICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  key: ZYNC_AUTHENTICATION_TOKEN
                  name: zync
            ### secret/backend-redis
            - name: BACKEND_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_URL
                  name: backend-redis
            - name: BACKEND_REDIS_SENTINEL_HOSTS
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_HOSTS
                  name: backend-redis
            - name: BACKEND_REDIS_SENTINEL_ROLE
              valueFrom:
                secretKeyRef:
                  key: REDIS_STORAGE_SENTINEL_ROLE
                  name: backend-redis
            ### secret/backend-listener
            - name: APICAST_BACKEND_ROOT_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: service_endpoint
                  name : system-backend-listener
            - name: BACKEND_ROUTE
              valueFrom:
                secretKeyRef:
                  key: service_endpoint
                  name : system-backend-listener
            - name: BACKEND_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  key: route_endpoint
                  name : system-backend-listener
            ### secret/backend-internal-api
            - name: CONFIG_INTERNAL_API_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: backend-internal-api
            - name: CONFIG_INTERNAL_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: backend-internal-api
            ### secret/system-multitenant-assets-s3
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: system-multitenant-assets-s3
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: system-multitenant-assets-s3
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  key: AWS_BUCKET_NAME
                  name: system-multitenant-assets-s3
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_BUCKET_REGION
                  name: system-multitenant-assets-s3
      # volumes
      volumes:
        - name: system-tmp
          emptyDir:
            medium: Memory
        - name: system-config
          secret:
            secretName: system-config
      # affinity
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: 3scale-api-management
                    threescale_component: system
                    threescale_component_element: sidekiq
            - weight: 99
              podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app: 3scale-api-management
                    threescale_component: system
                    threescale_component_element: sidekiq
