---

## Deployment
replicas: 1
image_name: "quay.io/3scale/apicast-cloud-hosted"
apicast_log_level: warn
apicast_oidc_log_level: notice
liveness_probe_initial_delay_seconds: 5
liveness_probe_timeout_seconds: 5
liveness_probe_period_seconds: 10
liveness_probe_success_threshold: 1
liveness_probe_failure_threshold: 3
readiness_probe_initial_delay_seconds: 5
readiness_probe_timeout_seconds: 5
readiness_probe_period_seconds: 30
readiness_probe_success_threshold: 1
readiness_probe_failure_threshold: 3
resources_requests_cpu: "500m"
resources_requests_memory: "64Mi"
resources_limits_cpu: "1"
resources_limits_memory: "128Mi"

## Service
load_balancer_proxy_protocol: "*"
load_balancer_cross_zone_load_balancing_enabled: true
load_balancer_connection_draining_enabled: true
load_balancer_connection_draining_timeout: 60
load_balancer_connection_healthcheck_healthy_threshold: 2
load_balancer_connection_healthcheck_unhealthy_threshold: 2
load_balancer_connection_healthcheck_interval: 5
load_balancer_connection_healthcheck_timeout: 3

## GrafanaDashboard
grafana_dashboard_label_key: "monitoring-key"
grafana_dashboard_label_value: "middleware"
