apiVersion: saas.3scale.net/v1alpha1
kind: EchoAPI
metadata:
  name: example
spec:
  image:
    tag: latest
  endpoint:
    dns:
      - echoapi.example.com
  marin3r:
    ports:
      - name: echo-api-http
        port: 38080
      - name: echo-api-https
        port: 38443
      - name: envoy-metrics
        port: 9901
    dynamicConfigs:
      - name: http
        listenerHttp:
          port: 38080
          routeConfigName: echo_api
      - name: https
        listenerHttp:
          port: 38443
          routeConfigName: echo_api
          certificateSecretName: certificate
          rateLimitOptions:
            domain: echo_api
            timeout: 10ms
            rateLimitCluster: test
      - name: echo_api_route
        rawConfig:
          type: "routeConfiguration"
          value:
            name: echo_api_route
            virtual_hosts:
              - domains:
                  - "*"
                name: echo_api
                routes:
                  - match:
                      prefix: /
                    route:
                      cluster: echo_api
      - name: echo_api_cluster
        cluster:
          port: 9292
          host: 127.0.0.1
      - name: runtime
        runtime:
          listenerNames: ["http"]
