apiVersion: saas.3scale.net/v1alpha1
kind: ShardedRedisBackup
metadata:
  labels:
    app.kubernetes.io/name: shardedredisbackup
    app.kubernetes.io/instance: shardedredisbackup-sample
    app.kubernetes.io/part-of: saas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: saas-operator
  name: shardedredisbackup-sample
spec:
  # TODO(user): Add fields here
