apiVersion: saas.3scale.net/v1alpha1
kind: System
metadata:
  name: system-sample
spec:
  image:
    tag: "nightly"
  env:
    ampRelease: 2.7.1
    rails:
      env: production
      logLevel: info
      logToStdout: true
    sandboxProxyOpensslVerifyMode: VERIFY_NONE
    forceSSL: true
    sslCertDir: /etc/pki/tls/cert
    threescaleProviderPlan: enterprise
    threescaleSuperdomain: example.com
  secret:
    multitenantIngressTLS: wildcard-multitenant-certificate
    appVaultPath: secret/data/openshift/cluster-example/3scale/system-app
    backendListenerVaultPath: secret/data/openshift/cluster-example/3scale/system-backend-listener
    configVaultPath: secret/data/openshift/dev-eng-ocp/3sscale-saas/system-config
    databaseVaultPath: secret/data/openshift/cluster-example/3scale/system-database
    eventsHookVaultPath: secret/data/openshift/cluster-example/3scale/system-events-hook
    masterApicastVaultPath: secret/data/openshift/cluster-example/3scale/system-master-apicast
    memcachedVaultPath: secret/data/openshift/cluster-example/3scale/system-memcached
    multitenantAssetsS3VaultPath: secret/data/openshift/cluster-example/3scale/system-multitenant-assets-s3
    recaptchaVaultPath: secret/data/openshift/cluster-example/3scale/system-recaptcha
    redisVaultPath: secret/data/openshift/cluster-example/3scale/system-redis
    seedVaultPath: secret/data/openshift/cluster-example/3scale/system-seed
    smtpVaultPath: secret/data/openshift/cluster-example/3scale/system-smtp
  app:
    replicas: 2
  sidekiq:
    replicas: 2
  sphinx:
    env:
      thinking:
        port: 9306
        bindAddress: "0.0.0.0"
        configFile: "/opt/sphinx/sphinx.conf"
        dbPath: "/opt/sphinx"
        pidFile: "/opt/sphinx/sphinx.pid"
      deltaIndexInterval: 5
      fullReindexInterval: 60
    resources:
      requests:
        cpu: "250m"
        memory: "4Gi"
      limits:
        cpu: "750m"
        memory: "5Gi"
      storage: "30Gi"