apiVersion: saas.3scale.net/v1alpha1
kind: EchoAPI
metadata:
  name: example
spec:
  image:
    tag: latest
  endpoint:
    dns:
      - echoapi.example.com
  marin3r:
    ports:
      - name: echo-api-http
        port: 38080
      - name: echo-api-https
        port: 38443
      - name: envoy-metrics
        port: 9901
