apiVersion: saas.3scale.net/v1alpha1
kind: Zync
metadata:
  name: example
spec:
  config:
    rails:
      environment: development
      logLevel: info
    databaseDSN:
      fromVault:
        path: secret/data/path/zync
        key: URL
    secretKeyBase:
      fromVault:
        path: secret/data/path/zync
        key: SECRET_KEY_BASE
    bugsnag:
      releaseStage: development
      apiKey:
        fromVault:
          path: secret/data/path/zync
          key: BUGSNAG_API_KEY
    zyncAuthToken:
      fromVault:
        path: secret/data/path/zync
        key: ZYNC_AUTHENTICATION_TOKEN
  api:
    hpa:
      minReplicas: 1
  que:
    hpa:
      minReplicas: 1
