apiVersion: saas.3scale.net/v1alpha1
kind: Backend
metadata:
  name: backend-sample
spec:
  image:
    tag: v2.101.1
  config:
    rackEnv: example
  secret:
    redisVaultPath: secret/data/openshift/cluster-example/3scale/backend-redis
    systemEventsHookVaultPath: secret/data/openshift/cluster-example/3scale/backend-system-events-hook
    internalApiVaultPath: secret/data/openshift/cluster-example/3scale/backend-internal-api
  listener:
    externalDnsHostname: backend.example.3scale.net
    marin3r:
      enabled: true
      annotations:
        marin3r.3scale.net/node-id: backend-listener
        marin3r.3scale.net/ports: backend-listener-http:38080,backend-listener-https:38443,envoy-metrics:9901
    replicas: 1
  worker:
    replicas: 1
  cron:
    replicas: 1
