apiVersion: saas.3scale.net/v1alpha1
kind: ShardedRedisBackup
metadata:
  name: backup
  namespace: default
spec:
  timeout: 5m
  schedule: "*/30 * * * *"
  sentinelRef: sentinel
  historyLimit: 10
  pollInterval: 10s
  dbFile: /data/dump.rdb
  sshOptions:
    privateKeySecretRef:
      name: redis-ssh-private-key
    user: root
  s3Options:
    bucket: my-bucket
    path: backups
    region: us-east-1
    credentialsSecretRef:
      name: aws-credentials
