apiVersion: saas.3scale.net/v1alpha1
kind: EchoAPI
metadata:
  name: example
spec:
  image:
    tag: latest
  endpoint:
    dns:
      - echoapi.example.com
  marin3r:
    ports:
      - name: echo-api-http
        port: 38080
      - name: echo-api-https
        port: 38443
      - name: envoy-metrics
        port: 9901
    envoyResources:
      - listenerHttp:
          name: http
          port: 38080
          routeConfigName: echo_api
      - listenerHttp:
          name: https
          port: 38080
          routeConfigName: echo_api
          certificateSecretName: certificate
      - routeConfiguration:
          name: echo_api
          virtualHosts:
            - name: echo_api
              domains: ["*"]
              routes:
                - {route: {cluster: echo_api}, match: {prefix: "/"}}
      - cluster:
          name: echo_api
          port: 9292
          host: 127.0.0.1
      - runtime:
          name: runtime
          listenerNames: ["http"]
