apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: system-app
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  name: system-app
  type: Opaque
  keysMap:
    ACCESS_CODE:
      path: {{ secret.app_vault_path }}
      key: ACCESS_CODE
    BUGSNAG_API_KEY:
      path: {{ secret.app_vault_path }}
      key: BUGSNAG_API_KEY
    DB_SECRET:
      path: {{ secret.app_vault_path }}
      key: DB_SECRET
    GITHUB_CLIENT_ID:
      path: {{ secret.app_vault_path }}
      key: GITHUB_CLIENT_ID
    GITHUB_CLIENT_SECRET:
      path: {{ secret.app_vault_path }}
      key: GITHUB_CLIENT_SECRET
    NEWRELIC_LICENSE_KEY:
      path: {{ secret.app_vault_path }}
      key: NEWRELIC_LICENSE_KEY
    PROMETHEUS_PASSWORD:
      path: {{ secret.app_vault_path }}
      key: PROMETHEUS_PASSWORD
    PROMETHEUS_USER:
      path: {{ secret.app_vault_path }}
      key: PROMETHEUS_USER
    RH_CUSTOMER_PORTAL_CLIENT_ID:
      path: {{ secret.app_vault_path }}
      key: RH_CUSTOMER_PORTAL_CLIENT_ID
    RH_CUSTOMER_PORTAL_CLIENT_SECRET:
      path: {{ secret.app_vault_path }}
      key: RH_CUSTOMER_PORTAL_CLIENT_SECRET
    SECRET_KEY_BASE:
      path: {{ secret.app_vault_path }}
      key: SECRET_KEY_BASE
    SEGMENT_DELETION_TOKEN:
      path: {{ secret.app_vault_path }}
      key: SEGMENT_DELETION_TOKEN
    SEGMENT_DELETION_WORKSPACE:
      path: {{ secret.app_vault_path }}
      key: SEGMENT_DELETION_WORKSPACE
    SEGMENT_WRITE_KEY:
      path: {{ secret.app_vault_path }}
      key: SEGMENT_WRITE_KEY
