apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: system-multitenant-assets-s3
  namespace: "{{ meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  name: system-multitenant-assets-s3
  type: Opaque
  keysMap:
    AWS_ACCESS_KEY_ID:
      path: {{ secret.multitenant_assets_s3_vault_path }}
      key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      path: {{ secret.multitenant_assets_s3_vault_path }}
      key: AWS_SECRET_ACCESS_KEY
    AWS_BUCKET_NAME:
      path: {{ secret.multitenant_assets_s3_vault_path }}
      key: AWS_BUCKET_NAME
    AWS_BUCKET_DOMAIN:
      path: {{ secret.multitenant_assets_s3_vault_path }}
      key: AWS_BUCKET_DOMAIN
    AWS_BUCKET_REGION:
      path: {{ secret.multitenant_assets_s3_vault_path }}
      key: AWS_BUCKET_REGION