apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: system-database
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  name: system-database
  type: Opaque
  keysMap:
    DB_HOST:
      path: {{ secret.database_vault_path }}
      key: DB_HOST
    DB_NAME:
      path: {{ secret.database_vault_path }}
      key: DB_NAME
    DB_USER:
      path: {{ secret.database_vault_path }}
      key: DB_USER
    DB_PASSWORD:
      path: {{ secret.database_vault_path }}
      key: DB_PASSWORD
    URL:
      path: {{ secret.database_vault_path }}
      key: URL