apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: system-redis
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  name: system-redis
  type: Opaque
  keysMap:
    ACTION_CABLE_REDIS_URL:
      path: {{ secret.redis_vault_path }}
      key: ACTION_CABLE_REDIS_URL
    MESSAGE_BUS_NAMESPACE:
      path: {{ secret.redis_vault_path }}
      key: MESSAGE_BUS_NAMESPACE
    MESSAGE_BUS_SENTINEL_HOSTS:
      path: {{ secret.redis_vault_path }}
      key: MESSAGE_BUS_SENTINEL_HOSTS
    MESSAGE_BUS_SENTINEL_ROLE:
      path: {{ secret.redis_vault_path }}
      key: MESSAGE_BUS_SENTINEL_ROLE
    MESSAGE_BUS_URL:
      path: {{ secret.redis_vault_path }}
      key: MESSAGE_BUS_URL
    NAMESPACE:
      path: {{ secret.redis_vault_path }}
      key: NAMESPACE
    SENTINEL_HOSTS:
      path: {{ secret.redis_vault_path }}
      key: SENTINEL_HOSTS
    SENTINEL_ROLE:
      path: {{ secret.redis_vault_path }}
      key: SENTINEL_ROLE
    URL:
      path: {{ secret.redis_vault_path }}
      key: URL