apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: system-smtp
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  name: system-smtp
  type: Opaque
  keysMap:
    address:
      path: {{ secret.smtp_vault_path }}
      key: address
    authentication:
      path: {{ secret.smtp_vault_path }}
      key: authentication
    port:
      path: {{ secret.smtp_vault_path }}
      key: port
    username:
      path: {{ secret.smtp_vault_path }}
      key: username
    password:
      path: {{ secret.smtp_vault_path }}
      key: password
    openssl_verify_mode:
      path: {{ secret.smtp_vault_path }}
      key: openssl_verify_mode
    enable_starttls_auto:
      path: {{ secret.smtp_vault_path }}
      key: enable_starttls_auto
