default: &default {}

s3: &s3
  # access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>" -> can't pass custom envvars to System, not supported
  access_key_id: admin
  # secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>" -> can't pass custom envvars to System, not supported
  secret_access_key: admin123
  role_arn: "<%= ENV['AWS_ROLE_ARN'] %>"
  web_identity_token_file: "<%= ENV['AWS_WEB_IDENTITY_TOKEN_FILE'] %>"
  role_session_name: <%= ENV['AWS_ROLE_SESSION_NAME'].presence || '3scale-porta' %>
  bucket: "<%= ENV['AWS_BUCKET'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
  # hostname: "<%= ENV['AWS_HOSTNAME'] %>" -> can't pass custom envvars to System, not supported
  hostname: "http://minio.minio.svc.cluster.local:9000"
  protocol: "<%= ENV['AWS_PROTOCOL'] %>"
  force_path_style: <%= ENV['AWS_PATH_STYLE'].presence || false %>

production:
  <<: *<%= ENV['FILE_UPLOAD_STORAGE'].presence || 'default' %>