{
 "title": "{{ meta.namespace }} / 3scale APIcast mapping-service",
 "tags": [
  "3scale",
  "apicast",
  "mapping-service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "{{ meta.namespace }}" },
   {
    "name": "pod",
    "query": "label_values(nginx_http_connections{pod=~'mapping-service.*'}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP connections (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'mapping-service.*'}[1m])) by (state)",
     "legendFormat": "{{ '{{state}}' }}"
    }
   ]
  },
  {
   "title": "HTTP connections (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_connections{namespace='$namespace', pod=~'$pod'}[1m])) by (pod,state)",
     "legendFormat": "{{ '{{pod}}: {{state}}' }}"
    }
   ]
  },
  {
   "title": "errors / min (${pod})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(nginx_error_log{namespace='$namespace',pod=~'$pod', level=~'error|crit|alert|emerg'}[1m])",
     "legendFormat": "{{ '{{pod}}: {{ level }}' }}"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'mapping-service.*', level=~'error|crit|alert|emerg'}[1h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 6h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'mapping-service.*', level=~'error|crit|alert|emerg'}[6h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 12h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'mapping-service.*', level=~'error|crit|alert|emerg'}[12h]))"
    }
   ]
  },
  {
   "title": "Total APIcast errors (last 24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(nginx_error_log{namespace='$namespace',pod=~'mapping-service.*', level=~'error|crit|alert|emerg'}[24h]))"
    }
   ]
  },
  {
   "title": "Used shared dictionaries space ($pod)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "100 - (openresty_shdict_free_space{namespace='$namespace',pod='$pod'} / openresty_shdict_capacity{namespace='$namespace',pod='$pod'} * 100)",
     "legendFormat": "{{ '{{dict}}' }}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'mapping-service.*'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'mapping-service.*'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'mapping-service.*'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'mapping-service.*'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'mapping-service.*'}",
     "legendFormat": "{{ '{{deployment}}-total-pods' }}"
    },
    {
     "expr": "kube_deployment_status_replicas_availablevailable{namespace='$namespace',deployment=~'mapping-service-.*'}",
     "legendFormat": "{{ '{{deployment}}-avail-pods' }}"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'mapping-service-.*'}",
     "legendFormat": "{{ '{{deployment}}-unavail-pods' }}"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'mapping-service-.*'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'mapping-service.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'mapping-service.*', container!=''}) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'mapping-service.*', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'mapping-service.*', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'mapping-service.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'mapping-service.*', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'apicast-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace', pod=~'mapping-service.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace', pod=~'mapping-service.*'}[5m])) by (pod)",
     "legendFormat": "{{ '{{pod}}' }}"
    }
   ]
  }
 ]
}