apiVersion: v1
kind: Service
metadata:
  name: mapping-service
  namespace: "{{ ansible_operator_meta.namespace }}"
  labels:
    app: mapping-service
    part-of: 3scale-saas
spec:
  type: ClusterIP
  ports:
    - name: mapping
      port: 80
      targetPort: mapping
  selector:
    deployment: mapping-service
