apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: echo-api
  namespace: "{{ meta.namespace }}"
  labels:
    app: echo-api
    threescale_component: echo-api
    threescale_component_element: echo-api
spec:
  podMetricsEndpoints:
    - interval: 60s
      path: /stats/prometheus
      port: envoy-metrics
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_service_label_app
          targetLabel: app
  selector:
    matchLabels:
      deployment: echo-api
