apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
  namespace: "{{ meta.namespace }}"
  labels:
    app: echo-api
    threescale_component: echo-api
    threescale_component_element: echo-api
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      deployment: echo-api
  template:
    metadata:
      labels:
        deployment: echo-api
        app: echo-api
        threescale_component: echo-api
        threescale_component_element: echo-api
{% if marin3r.enabled == true %}
        marin3r.3scale.net/status: "enabled"
{% if marin3r.annotations is defined %}
      annotations:
{# This is a hack to reverse the ansible operator -/_ convertion of dict keys #}
{%- for key in marin3r.annotations -%}
{% set key_replace = key | replace('_','-') %}
        {{ key_replace }}: {{ marin3r.annotations[key] | safe }}
{% endfor %}
{% endif %}
{% else %}
        marin3r.3scale.net/status: "disabled"
{% endif %}
    spec:
{% if image.pull_secret_name is defined %}
      imagePullSecrets:
        - name: "{{ image.pull_secret_name | default(image_pull_secret_name) }}"
{% endif %}
      containers:
        - name: echo-api
          image: "{{ image.name | default(image_name) }}:{{ image.tag | default(image_tag) }}"
          ports:
            - name: echo-api
              containerPort: 9292
          resources:
            requests:
              memory: "{{ resources.requests.memory | default(resources_requests_memory) }}"
              cpu: "{{ resources.requests.cpu | default(resources_requests_cpu) }}"
            limits:
              memory: "{{ resources.limits.memory | default(resources_limits_memory) }}"
              cpu: "{{ resources.limits.cpu | default(resources_limits_cpu) }}"
          livenessProbe:
            tcpSocket:
              port: echo-api
            initialDelaySeconds: {{ liveness_probe.initial_delay_seconds | default(liveness_probe_initial_delay_seconds) }}
            timeoutSeconds: {{ liveness_probe.timeout_seconds | default(liveness_probe_timeout_seconds) }}
            periodSeconds: {{ liveness_probe.period_seconds | default (liveness_probe_period_seconds) }}
            successThreshold: {{ liveness_probe.success_threshold | default(liveness_probe_success_threshold) }}
            failureThreshold: {{ liveness_probe.failure_threshold | default(liveness_probe_failure_threshold) }}
          readinessProbe:
            httpGet:
              path: /
              port: echo-api
              scheme: HTTP
            initialDelaySeconds: {{ readiness_probe.initial_delay_seconds | default(readiness_probe_initial_delay_seconds) }}
            timeoutSeconds: {{ readiness_probe.timeout_seconds | default(readiness_probe_timeout_seconds) }}
            periodSeconds: {{ readiness_probe.period_seconds | default(readiness_probe_period_seconds) }}
            successThreshold: {{ readiness_probe.success_threshold | default(readiness_probe_success_threshold) }}
            failureThreshold: {{ readiness_probe.failure_threshold | default(readiness_probe_failure_threshold) }}

