apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: default
resources:
  - autossl-redis
  - backend-redis
  - system-memcached
  - system-mysql
  - system-redis
  - zync-postgresql