# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/saas.3scale.net_apicasts.yaml
- bases/saas.3scale.net_autossls.yaml
- bases/saas.3scale.net_backends.yaml
- bases/saas.3scale.net_corsproxies.yaml
- bases/saas.3scale.net_echoapis.yaml
- bases/saas.3scale.net_mappingservices.yaml
- bases/saas.3scale.net_systems.yaml
- bases/saas.3scale.net_zyncs.yaml
# +kubebuilder:scaffold:crdkustomizeresource
