---

## Image
image_name: "quay.io/3scale/porta"
image_tag: "nightly"
image_pull_policy: "Always"

## GrafanaDashboard
grafana_dashboard_label_key: "monitoring-key"
grafana_dashboard_label_value: "middleware"

## Environment
env_amp_release: 2.7.1
env_force_ssl: true
env_ssl_cert_dir: "/etc/pki/tls/certs"
env_threescale_sandbox_proxy_openssl_verify_mode: "VERIFY_NONE"
env_threescale_superdomain: "localhost"
env_threescale_provider_plan: "enterprise"
env_rails_env: "preview"
env_rails_log_level: "info"
env_rails_log_to_stdout: true

##
## app
##

app_replicas: 2
### app > probe > liveness
app_liveness_probe_initial_delay_seconds: 30
app_liveness_probe_timeout_seconds: 1
app_liveness_probe_period_seconds: 10
app_liveness_probe_success_threshold: 1
app_liveness_probe_failure_threshold: 3
### app > probe > readiness
app_readiness_probe_initial_delay_seconds: 30
app_readiness_probe_timeout_seconds: 5
app_readiness_probe_period_seconds: 10
app_readiness_probe_success_threshold: 1
app_readiness_probe_failure_threshold: 3
### app > resources
app_resources_requests_cpu: "200m"
app_resources_requests_memory: "1Gi"
app_resources_limits_cpu: "400m"
app_resources_limits_memory: "2Gi"
### app > pdb
app_pdb_enabled: true
app_pdb_max_unavailable: 1
### app > hpa
app_hpa_enabled: true
app_hpa_min_replicas: 2
app_hpa_max_replicas: 4
app_hpa_resource_name: "cpu"
app_hpa_resource_utilization: 90

##
## sidekiq
##

sidekiq_replicas: 2
### sidekiq > probe > liveness
sidekiq_liveness_probe_initial_delay_seconds: 10
sidekiq_liveness_probe_timeout_seconds: 3
sidekiq_liveness_probe_period_seconds: 15
sidekiq_liveness_probe_success_threshold: 1
sidekiq_liveness_probe_failure_threshold: 5
### sidekiq > probe > readiness
sidekiq_readiness_probe_initial_delay_seconds: 10
sidekiq_readiness_probe_timeout_seconds: 5
sidekiq_readiness_probe_period_seconds: 30
sidekiq_readiness_probe_success_threshold: 1
sidekiq_readiness_probe_failure_threshold: 5
### sidekiq > resources
sidekiq_resources_requests_cpu: "500m"
sidekiq_resources_requests_memory: "1Gi"
sidekiq_resources_limits_cpu: "1"
sidekiq_resources_limits_memory: "2Gi"
### sidekiq > pdb
sidekiq_pdb_enabled: true
sidekiq_pdb_max_unavailable: 1
### sidekiq > hpa
sidekiq_hpa_enabled: true
sidekiq_hpa_min_replicas: 2
sidekiq_hpa_max_replicas: 4
sidekiq_hpa_resource_name: "cpu"
sidekiq_hpa_resource_utilization: 90

##
## sphinx
##

### sphinx > env > env
sphinx_env_thinking_port: 9306
sphinx_env_thinking_bind_address: "0.0.0.0"
sphinx_env_thinking_config_file: "/opt/system/db/sphinx/preview.conf"
sphinx_env_thinking_db_path: "/opt/system/db/sphinx"
sphinx_env_thinking_pid_file: "/opt/system/tmp/pids/searchd.pid"
sphinx_env_delta_index_interval: 5
sphinx_env_full_reindex_interval: 60
### sphinx > probe > liveness
sphinx_liveness_probe_initial_delay_seconds: 60
sphinx_liveness_probe_timeout_seconds: 3
sphinx_liveness_probe_period_seconds: 15
sphinx_liveness_probe_success_threshold: 1
sphinx_liveness_probe_failure_threshold: 5
### sphinx > probe > readiness
sphinx_readiness_probe_initial_delay_seconds: 60
sphinx_readiness_probe_timeout_seconds: 5
sphinx_readiness_probe_period_seconds: 30
sphinx_readiness_probe_success_threshold: 1
sphinx_readiness_probe_failure_threshold: 5
### sphinx > resources
sphinx_resources_requests_cpu: "250m"
sphinx_resources_requests_memory: "4Gi"
sphinx_resources_limits_cpu: "750m"
sphinx_resources_limits_memory: "5Gi"
sphinx_resources_storage: "30Gi"
