---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zyncs.saas.3scale.net
spec:
  group: saas.3scale.net
  names:
    kind: Zync
    listKind: ZyncList
    plural: zyncs
    singular: zync
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Zync is the Schema for the zyncs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec defines the desired state of Zync
          type: object
          x-kubernetes-preserve-unknown-fields: true
          required:
            - secret
          properties:
            image:
              type: object
              properties:
                name:
                  type: string
                  description: Image name (docker repository)
                tag:
                  type: string
                  description: Image tag
                pullSecretName:
                  type: string
                  description: Quay pull secret for private repository
            secret:
              type: object
              required:
                - vaultPath
              properties:
                vaultPath:
                  type: string
                  description: Vault Path with zync database secret definition
            zync:
              type: object
              properties:
                pdb:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Enable (true) or disable (false) PodDisruptionBudget
                    maxUnavailable:
                      type: string
                      pattern: "^[0-9]+%?$"
                      description: Maximum number of unavailable pods (number or percentage of pods)
                    minAvailable:
                      type: string
                      pattern: "^[0-9]+%?$"
                      description: Minimum number of available pods (number or percentage of pods), overrides maxUnavailable
                hpa:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Enable (true) or disable (false) HoritzontalPodAutoscaler
                    minReplicas:
                      type: integer
                      description: Minimum number of replicas
                    maxReplicas:
                      type: integer
                      description: Maximum number of replicas
                    resourceName:
                      type: string
                      description: Resource used for autoscale (cpu/memory)
                      enum:
                      - cpu
                      - memory
                    resourceUtilization:
                      type: integer
                      description: Percentage usage of the resource used for autoscale
                replicas:
                  type: integer
                  description: Number of replicas (ignored if hpa is enabled)
                env:
                  type: object
                  properties:
                    railsEnv:
                      type: string
                      description: Rails environment for zync
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "[0-9]+m?$"
                          description: Override CPU requests
                        memory:
                          type: string
                          pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                          description: Override Memory requests
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "[0-9]+m?$"
                          description: Override CPU limits
                        memory:
                          type: string
                          pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                          description: Override Memory limits
                livenessProbe:
                  type: object
                  properties:
                    timeoutSeconds:
                      type: integer
                      description: Override liveness probe timeout (seconds)
                    periodSeconds:
                      type: integer
                      description: Override liveness probe period (seconds)
                    successThreshold:
                      type: integer
                      description: Override liveness probe success threshold
                    failureThreshold:
                      type: integer
                      description: Override liveness probe failure threshold
                readinessProbe:
                  type: object
                  properties:
                    timeoutSeconds:
                      type: integer
                      description: Override readiness probe timeout (seconds)
                    periodSeconds:
                      type: integer
                      description: Override readiness probe period (seconds)
                    successThreshold:
                      type: integer
                      description: Override readiness probe success threshold
                    failureThreshold:
                      type: integer
                      description: Override readiness probe failure threshold
            que:
              type: object
              properties:
                pdb:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Enable (true) or disable (false) PodDisruptionBudget
                    maxUnavailable:
                      type: string
                      pattern: "^[0-9]+%?$"
                      description: Maximum number of unavailable pods (number or percentage of pods)
                    minAvailable:
                      type: string
                      pattern: "^[0-9]+%?$"
                      description: Minimum number of available pods (number or percentage of pods), overrides maxUnavailable
                hpa:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Enable (true) or disable (false) HoritzontalPodAutoscaler
                    minReplicas:
                      type: integer
                      description: Minimum number of replicas
                    maxReplicas:
                      type: integer
                      description: Maximum number of replicas
                    resourceName:
                      type: string
                      description: Resource used for autoscale (cpu/memory)
                      enum:
                      - cpu
                      - memory
                    resourceUtilization:
                      type: integer
                      description: Percentage usage of the resource used for autoscale
                replicas:
                  type: integer
                  description: Number of replicas (ignored if hpa is enabled)
                env:
                  type: object
                  properties:
                    railsEnv:
                      type: string
                      description: Rails environment for zync
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "[0-9]+m?$"
                          description: Override CPU requests
                        memory:
                          type: string
                          pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                          description: Override Memory requests
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "[0-9]+m?$"
                          description: Override CPU limits
                        memory:
                          type: string
                          pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                          description: Override Memory limits
                livenessProbe:
                  type: object
                  properties:
                    timeoutSeconds:
                      type: integer
                      description: Override liveness probe timeout (seconds)
                    periodSeconds:
                      type: integer
                      description: Override liveness probe period (seconds)
                    successThreshold:
                      type: integer
                      description: Override liveness probe success threshold
                    failureThreshold:
                      type: integer
                      description: Override liveness probe failure threshold
                readinessProbe:
                  type: object
                  properties:
                    timeoutSeconds:
                      type: integer
                      description: Override readiness probe timeout (seconds)
                    periodSeconds:
                      type: integer
                      description: Override readiness probe period (seconds)
                    successThreshold:
                      type: integer
                      description: Override readiness probe success threshold
                    failureThreshold:
                      type: integer
                      description: Override readiness probe failure threshold
            grafanaDashboard:
              type: object
              properties:
                label:
                  type: object
                  properties:
                    key:
                      type: string
                      description: Label key used by grafana-operator for dashboard discovery
                    value:
                      type: string
                      description: Label value used by grafana-operator for dashboard discovery
        status:
          description: Status defines the observed state of Zync
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
