kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-apicasts-admin-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
    - saas.3scale.net
  resources:
    - apicasts
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-apicasts-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
rules:
- apiGroups:
    - saas.3scale.net
  resources:
    - apicasts
  verbs:
    - get
    - list
    - watch