apiVersion: saas.3scale.net/v1alpha1
kind: AutoSSL
metadata:
  name: autossl
spec:
  image:
    name: REPLACE
    tag: REPLACE
    pullSecretName: pull-secrets
    pullPolicy: Always
  config:
    contactEmail: 3scale-operations@redhat.com
    domainWhitelist: []
    logLevel: debug
    proxyEndpoint: REPLACE
    redisHost: autossl-redis
    verificationEndpoint: REPLACE
  endpoint: {dns: [REPLACE]}
  hpa: {}
  pdb: {}
  replicas: 1
  resources: {}
