apiVersion: saas.3scale.net/v1alpha1
kind: AutoSSL
metadata:
  name: autossl
spec:
  image:
    name: REPLACE
    tag: REPLACE
    pullSecretName: pull-secrets
    pullPolicy: Always
  config:
    contactEmail: 3scale-operations@redhat.com
    domainWhitelist: []
    logLevel: debug
    proxyEndpoint: https://REPLACE
    redisHost: autossl-redis
    verificationEndpoint: https://REPLACE/swagger/spec.json
  hpa: {}
  pdb: {}
  resources: {}
  replicas: 1
  publishingStrategies:
    endpoints:
      - name: Proxy
        strategy: Simple
        simple:
          externalDnsHostnames: [REPLACE]
