apiVersion: saas.3scale.net/v1alpha1
kind: CORSProxy
metadata:
  name: cors-proxy
spec:
  image:
    name: REPLACE
    tag: REPLACE
    pullSecretName: pull-secrets
    pullPolicy: Always
  config:
    systemDatabaseDSN: {fromSeed: {}}
  hpa: {}
  pdb: {}
  replicas: 1
  resources: {}
