apiVersion: saas.3scale.net/v1alpha1
kind: MappingService
metadata:
  name: mapping-service
spec:
  config:
    apiHost: REPLACE
    systemAdminToken: {fromSeed: {}}
  image:
    name: REPLACE
    tag: REPLACE
    pullSecretName: pull-secrets
    pullPolicy: Always
  hpa: {}
  pdb: {}
  replicas: 1
  resources: {}
