---
apiVersion: saas.3scale.net/v1alpha1
kind: Zync
metadata:
  name: zync
spec:
  image:
      name: REPLACE
      tag: REPLACE
      pullSecretName: pull-secrets
      pullPolicy: Always
  config:
    databaseDSN: {fromSeed: {}}
    rails:
      environment: production
      logLevel: info
    secretKeyBase: {fromSeed: {}}
    zyncAuthToken: {fromSeed: {}}
  api:
    hpa: {}
    pdb: {}
    replicas: 1
    resources: {}
  console:
    enabled: true
    resources: {}
  que:
    hpa: {}
    pdb: {}
    replicas: 1
    resources: {}
