name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin

      - name: Run tests
        run: make test

      - name: Run e2e tests
        run: make test-e2e

      - name: Build image
        run: make docker-build

      - name: Export release name
        run: |
          echo "NEW_RELEASE=$(make get-new-release)" >> $GITHUB_ENV

      - name: Login to quay.io/3scale
        if: ${{ env.NEW_RELEASE != '' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push new operator image
        if: ${{ env.NEW_RELEASE != '' }}
        run: make docker-push

      - name: Publish new bundle image in saas-operator catalog
        if: ${{ env.NEW_RELEASE != '' }}
        run: make bundle-publish

      - name: Create a new draft-release in github
        if: ${{ env.NEW_RELEASE != '' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.NEW_RELEASE }}"
          title: "${{ env.NEW_RELEASE }}"
          draft: true