name: test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin

      - name: Run tests
        run: make test

      - name: Run e2e tests
        run: make test-e2e
