name: test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - uses: actions/cache@v2
        with:
          path: ./testbin
          key: ${{ runner.os }}-testbin

      - uses: actions/cache@v2
        with:
          path: ./bin
          key: ${{ runner.os }}-bin

      - name: Run tests
        run: |
          make test
